import "HostAndProcess.idl";

namespace ScratchIsland
{
    [default_interface] runtimeclass HostManager // : IScratchInterface
    {
        HostManager();

        Windows.Foundation.Collections.IObservableVector<HostAndProcess> Hosts { get; };
        HostAndProcess CreateHost();
    };
}
