import "ocidl.idl";

declare_guid(CLSID_ICalculatorProxy, 1111d2f1-1c69-4c91-949e-12345a85bdc5);

[uuid(0DBABB94-CE99-42F7-ACBD-E698B2332C60), version(1.0)]
interface ICalculatorComponent : IUnknown
{
    HRESULT Add([in] int a, [in] int b, [out, retval] int* value);
}
