// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen
#include "pch.h"
#include "common.h"
#include "TabViewAutomationPeer.h"

namespace winrt::Microsoft::UI::Xaml::Automation::Peers
{
    CppWinRTActivatableClassWithBasicFactory(TabViewAutomationPeer)
}

#include "TabViewAutomationPeer.g.cpp"
