// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// DO NOT EDIT! This file was generated by CustomTasks.DependencyPropertyCodeGen
#pragma once

class TabViewItemTemplateSettingsProperties
{
public:
    TabViewItemTemplateSettingsProperties();

    void IconElement(winrt::IconElement const& value);
    winrt::IconElement IconElement();

    void TabGeometry(winrt::Geometry const& value);
    winrt::Geometry TabGeometry();

    static winrt::DependencyProperty IconElementProperty() { return s_IconElementProperty; }
    static winrt::DependencyProperty TabGeometryProperty() { return s_TabGeometryProperty; }

    static GlobalDependencyProperty s_IconElementProperty;
    static GlobalDependencyProperty s_TabGeometryProperty;

    static void EnsureProperties();
    static void ClearProperties();
};
