// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings
{
    enum CursorStyle
    {
        Vintage,
        Bar,
        Underscore,
        FilledBox,
        EmptyBox
    };

    interface ICoreSettings
    {
        UInt32 DefaultForeground;
        UInt32 DefaultBackground;
        UInt32 GetColorTableEntry(Int32 index);
        void SetColorTableEntry(Int32 index, UInt32 value);
        // TODO:MSFT:20642297 - define a sentinel for Infinite Scrollback
        Int32 HistorySize;
        Int32 InitialRows;
        Int32 InitialCols;
        Boolean SnapOnInput;

        UInt32 CursorColor;
        CursorStyle CursorShape;
        UInt32 CursorHeight;
        String StartingTitle;
        Boolean SuppressApplicationTitle;
        String WordDelimiters;
        Boolean CopyOnSelect;
    };

}
