

namespace ScratchWinRTServer
{
    [default_interface] runtimeclass HostClass {
        HostClass(Guid g);
        void DoTheThing();
        Int32 DoCount { get; };
        Guid Id { get; };
    };
}
