

namespace ScratchWinRTServer
{
    [default_interface] runtimeclass ScratchClass // : IScratchInterface
    {
        ScratchClass();
        String DoTheThing();
        Windows.UI.Xaml.Controls.Button MyButton { get; };
    };
}
