namespace Microsoft.Terminal.Settings.Editor.Model
{
    runtimeclass ColorScheme : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        // Background
        Windows.UI.Color Background;
        String BackgroundHexValue;
        Windows.UI.Xaml.Media.Brush BackgroundBrush { get; };

        //Foreground
        Windows.UI.Color Foreground;
        String ForegroundHexValue;
        Windows.UI.Xaml.Media.Brush ForegroundBrush { get; };

        // Black
        Windows.UI.Color Black;
        String BlackHexValue;
        Windows.UI.Xaml.Media.Brush BlackBrush { get; };

        // BrightBlack
        Windows.UI.Color BrightBlack;
        String BrightBlackHexValue;
        Windows.UI.Xaml.Media.Brush BrightBlackBrush { get; };

        // Blue
        Windows.UI.Color Blue;
        String BlueHexValue;
        Windows.UI.Xaml.Media.Brush BlueBrush { get; };

        // BrightBlue
        Windows.UI.Color BrightBlue;
        String BrightBlueHexValue;
        Windows.UI.Xaml.Media.Brush BrightBlueBrush { get; };

        // Cyan
        Windows.UI.Color Cyan;
        String CyanHexValue;
        Windows.UI.Xaml.Media.Brush CyanBrush { get; };

        // BrightCyan
        Windows.UI.Color BrightCyan;
        String BrightCyanHexValue;
        Windows.UI.Xaml.Media.Brush BrightCyanBrush { get; };

        // Green
        Windows.UI.Color Green;
        String GreenHexValue;
        Windows.UI.Xaml.Media.Brush GreenBrush { get; };

        // BrightGreen
        Windows.UI.Color BrightGreen;
        String BrightGreenHexValue;
        Windows.UI.Xaml.Media.Brush BrightGreenBrush { get; };

        // Purple
        Windows.UI.Color Purple;
        String PurpleHexValue;
        Windows.UI.Xaml.Media.Brush PurpleBrush { get; };

        // BrightPurple
        Windows.UI.Color BrightPurple;
        String BrightPurpleHexValue;
        Windows.UI.Xaml.Media.Brush BrightPurpleBrush { get; };

        // Red
        Windows.UI.Color Red;
        String RedHexValue;
        Windows.UI.Xaml.Media.Brush RedBrush { get; };

        // BrightRed
        Windows.UI.Color BrightRed;
        String BrightRedHexValue;
        Windows.UI.Xaml.Media.Brush BrightRedBrush { get; };

        // White
        Windows.UI.Color White;
        String WhiteHexValue;
        Windows.UI.Xaml.Media.Brush WhiteBrush { get; };

        // BrightWhite
        Windows.UI.Color BrightWhite;
        String BrightWhiteHexValue;
        Windows.UI.Xaml.Media.Brush BrightWhiteBrush { get; };

        // Yellow
        Windows.UI.Color Yellow;
        String YellowHexValue;
        Windows.UI.Xaml.Media.Brush YellowBrush { get; };

        // BrightYellow
        Windows.UI.Color BrightYellow;
        String BrightYellowHexValue;
        Windows.UI.Xaml.Media.Brush BrightYellowBrush { get; };
    }
}
