// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor.Model
{
    enum TabViewWidthMode
    {
        equal,
        titleLength,
        compact
    };
    enum AppLaunchMode
    {
        Default,
        maximized
    };

    runtimeclass GlobalSettings : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        //String UnparsedDefaultProfile();

        String DefaultProfile;
        Int32 InitialRows;
        Int32 InitialCols;
        Boolean AlwaysShowTabs;
        Boolean ShowTitleInTitlebar;
        Boolean ShowTitlebar;
        Boolean ConfirmCloseAllTabs;
        Windows.UI.Xaml.ElementTheme Theme;
        TabViewWidthMode TabWidthMode;
        AppLaunchMode LaunchMode;
        Boolean ShowTabsInTitlebar;
        String WordDelimiters;
        Boolean CopyOnSelect;
        Boolean CopyFormatting;
        Boolean WarnAboutLargePaste;
        Boolean WarnAboutMultiLinePaste;
        String LaunchPosition;
        // fix JsonConverters for these unique types
        //LaunchPosition InitialPosition;
        //AppLaunchMode LaunchMode;
        Boolean SnapToGridOnResize;
        Boolean ForceFullRepaintRendering;
        Boolean SoftwareRendering;
        Boolean ForceVTInput;
        Boolean DebugFeaturesEnabled;
        Boolean StartOnUserLogin;
        Boolean AlwaysOnTop;
        Boolean DisableDynamicProfiles;
    }
}
