namespace Microsoft.Terminal.Settings.Editor.Model
{
    enum CloseOnExitMode
    {
        graceful,
        always,
        never
    };

    enum ScrollbarState
    {
        visible,
        Hidden
    };

    enum FontWeight
    {
        thin,
        extra_light,
        light,
        semi_light,
        normal,
        medium,
        semi_bold,
        bold,
        extra_bold,
        black,
        extra_black
    };

    enum Stretch
    {
        none,
        fill,
        uniform,
        uniformToFill
    };

    enum TextAntialiasingMode
    {
        grayscale,
        cleartype,
        aliased
    };

    enum CursorStyle
    {
        vintage,
        bar,
        underscore,
        filledBox,
        emptyBox
    };

    runtimeclass Profile : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Guid Guid;
        String Name;
        String Source;
        Guid ConnectionType;
        String Icon;
        Boolean Hidden;
        CloseOnExitMode CloseOnExit;
        String TabTitle;

        // Terminal Control Settings
        Boolean UseAcrylic;
        Double AcrylicOpacity;
        ScrollbarState ScrollState;

        String FontFace;
        Int32 FontSize;
        Windows.UI.Text.FontWeight FontWeight;
        String Padding;

        Boolean CopyOnSelect;

        String Commandline;
        String StartingDirectory;
        String EnvironmentVariables;

        String BackgroundImage;
        Double BackgroundImageOpacity;
        Windows.UI.Xaml.Media.Stretch BackgroundImageStretchMode;
        Windows.UI.Xaml.HorizontalAlignment BackgroundImageHorizontalAlignment;
        Windows.UI.Xaml.VerticalAlignment BackgroundImageVerticalAlignment;

        UInt32 SelectionBackground;

        TextAntialiasingMode AntialiasingMode;

        Boolean RetroTerminalEffect;
        Boolean ForceFullRepaintRendering;
        Boolean SoftwareRendering;

        // Terminal Core Settings
        UInt32 DefaultForeground;
        UInt32 DefaultBackground;
        String ColorScheme;

        // TODO:MSFT:20642297 - define a sentinel for Infinite Scrollback
        Int32 HistorySize;
        Int32 InitialRows;
        Int32 InitialCols;

        Boolean SnapOnInput;
        Boolean AltGrAliasing;

        UInt32 CursorColor;
        CursorStyle CursorShape;
        UInt32 CursorHeight;
        String StartingTitle;
        Boolean SuppressApplicationTitle;

        Boolean ForceVTInput;
    }
}
