// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace SettingsControl
{
    enum CloseOnExitMode
    {
        Never,
        Graceful,
        Always
    };

    struct LaunchPosition
    {
        Windows.Foundation.IReference<Int32> X;
        Windows.Foundation.IReference<Int32> Y;
    };

    enum AppLaunchMode
    {
        DefaultMode,
        MaximizedMode,
        FullscreenMode
    };

    enum CursorStyle
    {
        Vintage,
        Bar,
        Underscore,
        FilledBox,
        EmptyBox
    };

    enum Direction
    {
        None = 0,
        Left,
        Right,
        Up,
        Down
    };

    enum SplitState
    {
        Automatic = -1,
        None = 0,
        Vertical = 1,
        Horizontal = 2
    };

    enum SplitType
    {
        Manual = 0,
        Duplicate = 1
    };

    enum SettingsTarget
    {
        SettingsFile = 0,
        DefaultsFile,
        AllFiles
    };

    enum ScrollbarState
    {
        Visible = 0,
        Hidden
    };

    enum TextAntialiasingMode
    {
        Grayscale = 0,
        Cleartype,
        Aliased
    };

    // This is a 1-to-1 translation of MUX::TabViewWidthMode
    enum TabWidthMode
    {
        Equal = 0,
        TitleLength,
        Compact
    };
}
