// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{
    [default_interface]
    runtimeclass AsciicastConnection : ITerminalConnection
    {
        AsciicastConnection();

        UInt32 InitialCols { get; };
        UInt32 InitialRows { get; };

        Double TotalDuration { get; };
        Double CurrentPosition { get; };
        Double PlaybackSpeed { get; set; };

        void PausePlayback();
        void ResumePlayback();
        void SeekPlayback(Double position);
        void RestartPlayback();

        Boolean IsPaused { get; };

        event Windows.Foundation.TypedEventHandler<AsciicastConnection, Object> PlaybackPositionChanged;
        event Windows.Foundation.TypedEventHandler<AsciicastConnection, Object> PlaybackStateChanged;
    };

}
