// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{
    [default_interface] runtimeclass ConptyConnection : ITerminalConnection
    {
        ConptyConnection();
        Guid Guid { get; };

        static event NewConnectionHandler NewConnection;
        static void StartInboundListener();
        static void StopInboundListener();
    };
}
