// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.Connection
{
    [default_interface]
    runtimeclass EchoConnection : ITerminalConnection
    {
        EchoConnection();
    };

}
