// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalConnection
{
    enum ConnectionState
    {
        NotConnected = 0,
        Connecting,
        Connected,
        Closing,
        Closed,
        Failed
    };

    delegate void TerminalOutputEventArgs(String output);
    delegate void StateChangedEventArgs(ITerminalConnection connection, ConnectionState newState);

    /*
    [default_interface] runtimeclass StateChangedEventArgs
    {
        ConnectionState State { get; }
    }
    */

    interface ITerminalConnection
    {
        event TerminalOutputEventArgs TerminalOutput;

        event StateChangedEventArgs StateChanged;
        //ConnectionState State { get; };

        void Start();
        void WriteInput(String data);
        void Resize(UInt32 rows, UInt32 columns);
        void Close();
    };

}
