// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalConnection
{
    enum VisualConnectionState{
		NotConnected,
        Connecting,
        ConnectionFailed,
        Connected,
        Disconnecting,
        DisconnectedGracefully,
        DisconnectedNotGracefully
    };

    delegate void TerminalOutputEventArgs(String output);
    delegate void TerminalDisconnectedEventArgs(Boolean graceful, Boolean canReconnect);
    delegate void StateChangedEventArgs(VisualConnectionState visualConnectionState, Boolean allowUserInput);

    interface ITerminalConnection
    {
        event TerminalOutputEventArgs TerminalOutput;
        event TerminalDisconnectedEventArgs TerminalDisconnected;
        event StateChangedEventArgs StateChanged;

        void Start();
        void WriteInput(String data);
        void Resize(UInt32 rows, UInt32 columns);
        void Close();

        String GetTabTitle(String previousTitle);
    };
}
