// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{

    [default_interface] runtimeclass PipeConnection : ITerminalConnection
    {
        static Guid ConnectionType { get; };

        PipeConnection();
        Guid Guid { get; };
        String Commandline { get; };

        void ClearBuffer();

        void ShowHide(Boolean show);

        void ReparentWindow(UInt64 newParent);

    };
}
