// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{
    [default_interface]
    runtimeclass TelnetConnection : ITerminalConnection
    {
        static Guid ConnectionType { get; };
        TelnetConnection(String uri);
    };

}
