// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{
    [default_interface]
    runtimeclass TmuxConnection : ITerminalConnection
    {
        TmuxConnection();

        void WriteOutput(Char[] data);
        event TerminalOutputHandler TerminalInput;
    };
}
