import "oaidl.idl";
import "ocidl.idl";

#include "ConsoleComGuids.h"
cpp_quote("#include \"ConsoleComGuids.h\"")

[
    object,
    uuid(__IID_ITerminalHandoff)
] interface ITerminalHandoff : IUnknown
{
    HRESULT DoNothing();

    HRESULT EstablishHandoff([in, system_handle(sh_pipe)] HANDLE in,
                             [in, system_handle(sh_pipe)] HANDLE out,
                             [in, system_handle(sh_pipe)] HANDLE signal);
};
