// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "Command.idl";

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface] runtimeclass ActionMap {
        UInt64 KeybindingCount { get; };
        UInt64 CommandCount { get; };

        Command GetActionByName(String name);
        Command GetActionByKeyChord(Microsoft.Terminal.Control.KeyChord keys);

        Microsoft.Terminal.Control.KeyChord GetKeyBindingForAction(ShortcutAction action);
        Microsoft.Terminal.Control.KeyChord GetKeyBindingForAction(ShortcutAction action, IActionArgs actionArgs);

        Windows.Foundation.Collections.IMapView<String, Command> NameMap { get; };

        //ActionAndArgs TryLookup(Microsoft.Terminal.Control.KeyChord chord);

        //UInt64 Size();
        //
        //void SetKeyBinding(ActionAndArgs actionAndArgs, Microsoft.Terminal.Control.KeyChord chord);
        //void ClearKeyBinding(Microsoft.Terminal.Control.KeyChord chord);
        //
        //Microsoft.Terminal.Control.KeyChord GetKeyBindingForAction(ShortcutAction action);
        //Microsoft.Terminal.Control.KeyChord GetKeyBindingForActionWithArgs(ActionAndArgs actionAndArgs);
    }
}
