// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "IInheritable.idl.h"

namespace Microsoft.Terminal.Settings.Model
{
    enum LLMProvider
    {
        AzureOpenAI,
        OpenAI,
        GithubCopilot
    };

    [default_interface] runtimeclass AIConfig {
        INHERITABLE_SETTING(LLMProvider, ActiveProvider);

        String AzureOpenAIEndpoint;
        String AzureOpenAIKey;
        String OpenAIKey;
        String GithubCopilotAuthToken;
        String GithubCopilotRefreshToken;
    }
}
