// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IAppearanceConfig.idl";
import "ISettingsModelObject.idl";

namespace Microsoft.Terminal.Settings.Model
{
    runtimeclass AppearanceConfig : [default] IAppearanceConfig, IMediaResourceContainer {
    }
}
