// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IAppearanceConfig.idl";

namespace Microsoft.Terminal.Settings.Model
{
    runtimeclass AppearanceConfig : [default] IAppearanceConfig {
    }
}
