// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "GlobalAppSettings.idl";
import "Profile.idl";
import "TerminalWarnings.idl";

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface] runtimeclass CascadiaSettings {
        static CascadiaSettings LoadDefaults();
        static CascadiaSettings LoadAll();
        static CascadiaSettings LoadUniversal();

        static String SettingsPath { get; };
        static String DefaultSettingsPath { get; };

        static String ApplicationDisplayName { get; };
        static String ApplicationVersion { get; };

        GlobalAppSettings GlobalSettings { get; };

        Windows.Foundation.Collections.IObservableVector<Profile> Profiles { get; };

        KeyMapping KeyMap { get; };

        Windows.Foundation.Collections.IVectorView<SettingsLoadWarnings> Warnings { get; };
        Windows.Foundation.IReference<SettingsLoadErrors> GetLoadingError { get; };
        String GetSerializationErrorMessage { get; };

        Profile FindProfile(Guid profileGuid);
        ColorScheme GetColorSchemeForProfile(Guid profileGuid);

        Guid GetProfileForArgs(NewTerminalArgs newTerminalArgs);
    }
}
