// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface] runtimeclass ColorScheme {
        ColorScheme(String name);

        String Name;

        Windows.UI.Color Foreground;
        Windows.UI.Color Background;
        Windows.UI.Color SelectionBackground;
        Windows.UI.Color CursorColor;

        // winrt::com_arrays prevent data binding.
        // Instead of representing Table as a property,
        // we expose the getter as a function.
        Windows.UI.Color[] Table();
        void SetColorTableEntry(UInt8 index, Windows.UI.Color value);
    }
}
