// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface] runtimeclass ColorScheme {
        ColorScheme();

        String Name;

        Windows.UI.Color Foreground;
        Windows.UI.Color Background;
        Windows.UI.Color SelectionBackground;
        Windows.UI.Color CursorColor;

        Windows.UI.Color[] Table { get; };
        void SetColorTableEntry(UInt8 index, Windows.UI.Color value);
    }
}
