// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "Profile.idl";
#include "IInheritable.idl.h"

#define INHERITABLE_FONT_SETTING(Type, Name) \
    _BASE_INHERITABLE_SETTING(Type, Name);      \
    Microsoft.Terminal.Settings.Model.FontConfig Name##OverrideSource { get; }

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface] runtimeclass FontConfig {
        Microsoft.Terminal.Settings.Model.Profile SourceProfile { get; };

        INHERITABLE_FONT_SETTING(String, FontFace);
        INHERITABLE_FONT_SETTING(Int32, FontSize);
        INHERITABLE_FONT_SETTING(Windows.UI.Text.FontWeight, FontWeight);

        // The INHERITABLE_FONT_SETTING macro doesn't like Windows.Foundation.Collections.IMap<String, UInt32>
        // (possibly because of the comma) so features and axes are being declared manually for now
        Windows.Foundation.Collections.IMap<String, UInt32> FontFeatures;
        Boolean HasFontFeatures { get; };
        void ClearFontFeatures();
        Microsoft.Terminal.Settings.Model.FontConfig FontFeaturesOverrideSource { get; };

        Windows.Foundation.Collections.IMap<String, Int32> FontAxes;
        Boolean HasFontAxes { get; };
        void ClearFontAxes();
        Microsoft.Terminal.Settings.Model.FontConfig FontAxesOverrideSource { get; };
    }
}
