// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "IInheritable.idl.h"

#define INHERITABLE_PROFILE_SETTING(Type, Name) \
    _BASE_INHERITABLE_SETTING(Type, Name);      \
    Microsoft.Terminal.Settings.Model.IAppearanceConfig Name##OverrideSource { get; }

namespace Microsoft.Terminal.Settings.Model
{
    [flags] enum ConvergedAlignment {
        // low 4 bits are the horizontal
        Horizontal_Center = 0x00,
        Horizontal_Left = 0x01,
        Horizontal_Right = 0x02,

        // high 4 bits are the vertical
        Vertical_Center = 0x00,
        Vertical_Top = 0x10,
        Vertical_Bottom = 0x20
    };

    interface IAppearanceConfig
    {
        INHERITABLE_PROFILE_SETTING(String, ColorSchemeName);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, Foreground);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, Background);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, SelectionBackground);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, CursorColor);
        INHERITABLE_PROFILE_SETTING(Microsoft.Terminal.Core.CursorStyle, CursorShape);
        INHERITABLE_PROFILE_SETTING(UInt32, CursorHeight);

        INHERITABLE_PROFILE_SETTING(String, BackgroundImagePath);
        String ExpandedBackgroundImagePath { get; };

        INHERITABLE_PROFILE_SETTING(Double, BackgroundImageOpacity);
        INHERITABLE_PROFILE_SETTING(Windows.UI.Xaml.Media.Stretch, BackgroundImageStretchMode);
        INHERITABLE_PROFILE_SETTING(ConvergedAlignment, BackgroundImageAlignment);

        INHERITABLE_PROFILE_SETTING(Boolean, RetroTerminalEffect);
        INHERITABLE_PROFILE_SETTING(String, PixelShaderPath);
    };
}
