// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{
    [flags] enum ConvergedAlignment {
        // low 4 bits are the horizontal
        Horizontal_Center = 0x00,
        Horizontal_Left = 0x01,
        Horizontal_Right = 0x02,

        // high 4 bits are the vertical
        Vertical_Center = 0x00,
        Vertical_Top = 0x10,
        Vertical_Bottom = 0x20
    };

    // [default_interface]
    interface IAppearanceConfig
    {
        Boolean HasColorSchemeName();
        void ClearColorSchemeName();
        String ColorSchemeName;

        Boolean HasForeground();
        void ClearForeground();
        Windows.Foundation.IReference<Windows.UI.Color> Foreground;

        Boolean HasBackground();
        void ClearBackground();
        Windows.Foundation.IReference<Windows.UI.Color> Background;

        Boolean HasSelectionBackground();
        void ClearSelectionBackground();
        Windows.Foundation.IReference<Windows.UI.Color> SelectionBackground;

        Boolean HasCursorColor();
        void ClearCursorColor();
        Windows.Foundation.IReference<Windows.UI.Color> CursorColor;

        Boolean HasCursorShape();
        void ClearCursorShape();
        Microsoft.Terminal.TerminalControl.CursorStyle CursorShape;

        Boolean HasCursorHeight();
        void ClearCursorHeight();
        UInt32 CursorHeight;

        Boolean HasBackgroundImagePath();
        void ClearBackgroundImagePath();
        String BackgroundImagePath;
        String ExpandedBackgroundImagePath { get; };

        Boolean HasBackgroundImageOpacity();
        void ClearBackgroundImageOpacity();
        Double BackgroundImageOpacity;

        Boolean HasBackgroundImageStretchMode();
        void ClearBackgroundImageStretchMode();
        Windows.UI.Xaml.Media.Stretch BackgroundImageStretchMode;

        Boolean HasBackgroundImageAlignment();
        void ClearBackgroundImageAlignment();
        ConvergedAlignment BackgroundImageAlignment;
    };
}
