// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{
    // See https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart

    // We use the default attribute to declare IValueConverter as the default
    // interface. In the listing, IconPathConverter has only a
    // constructor, and no methods, so no default interface is generated for it.
    // The default attribute is optimal if you won't be adding instance members
    // to IconPathConverter, because no QueryInterface will be
    // required to call the IValueConverter methods
    runtimeclass IconPathConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        IconPathConverter();

        static Windows.UI.Xaml.Controls.IconElement IconWUX(String path);
        static Microsoft.UI.Xaml.Controls.IconSource IconSourceMUX(String path);
    };

}
