// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "AllShortcutActions.h"

import "ActionArgs.idl";

namespace Microsoft.Terminal.Settings.Model
{
    enum ShortcutAction
    {
        Invalid = 0,

        // When adding a new action, add them to AllShortcutActions.h!
        #define ON_ALL_ACTIONS(action) action,
        ALL_SHORTCUT_ACTIONS
        #undef ON_ALL_ACTIONS
    };

    [default_interface] runtimeclass ActionAndArgs {
        ActionAndArgs();
        ActionAndArgs(ShortcutAction action, IActionArgs args);

        IActionArgs Args;
        ShortcutAction Action;
    };

    [default_interface] runtimeclass KeyMapping
    {
        ActionAndArgs TryLookup(Microsoft.Terminal.Control.KeyChord chord);
        UInt64 Size();

        void SetKeyBinding(ActionAndArgs actionAndArgs, Microsoft.Terminal.Control.KeyChord chord);
        void ClearKeyBinding(Microsoft.Terminal.Control.KeyChord chord);

        Microsoft.Terminal.Control.KeyChord GetKeyBindingForAction(ShortcutAction action);
        Microsoft.Terminal.Control.KeyChord GetKeyBindingForActionWithArgs(ActionAndArgs actionAndArgs);
    }
}
