/*++
Copyright (c) Microsoft Corporation
Licensed under the MIT license.

Module Name:
- SeparatorEntry.h

Abstract:
- An entry in the "new tab" dropdown menu that represents a collection
    of profiles that are all generated by the same source/generator.

Author(s):
- Floris Westerman - August 2022

--*/
#pragma once

#include "pch.h"
#include "ProfileCollectionEntry.h"
#include "ProfilesSourceEntry.g.h"
#include "JsonUtils.h"
#include "Profile.h"

namespace winrt::Microsoft::Terminal::Settings::Model::implementation
{
    struct ProfilesSourceEntry : ProfilesSourceEntryT<ProfilesSourceEntry, ProfileCollectionEntry>
    {
    public:
        ProfilesSourceEntry() noexcept;
        explicit ProfilesSourceEntry(const winrt::hstring& source) noexcept;

        Json::Value ToJson() const override;
        static com_ptr<NewTabMenuEntry> FromJson(const Json::Value& json);

        WINRT_PROPERTY(winrt::hstring, Source);
    };
}

namespace winrt::Microsoft::Terminal::Settings::Model::factory_implementation
{
    BASIC_FACTORY(ProfilesSourceEntry);
}
