// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "IInheritable.idl.h"

#define INHERITABLE_PROFILE_SETTING(Type, Name) \
    _BASE_INHERITABLE_SETTING(Type, Name);      \
    Microsoft.Terminal.Settings.Model.Profile Name##OverrideSource { get; }

namespace Microsoft.Terminal.Settings.Model
{
    // This tag is used to identify the context in which the Profile was created
    enum OriginTag
    {
        Custom = 0,
        InBox,
        Generated,
        Fragment
    };

    enum CloseOnExitMode
    {
        Never = 0,
        Graceful,
        Always
    };

    [flags]
    enum BellStyle
    {
        Audible = 0x1,
        Visual = 0x2,
        All = 0xffffffff
    };

    [flags]
    enum ConvergedAlignment {
        // low 4 bits are the horizontal
        Horizontal_Center = 0x00,
        Horizontal_Left = 0x01,
        Horizontal_Right = 0x02,

        // high 4 bits are the vertical
        Vertical_Center = 0x00,
        Vertical_Top = 0x10,
        Vertical_Bottom = 0x20
    };

    [default_interface] runtimeclass Profile : Windows.Foundation.IStringable {
        Profile();
        Profile(Guid guid);

        OriginTag Origin { get; };

        INHERITABLE_PROFILE_SETTING(String, Name);

        Boolean HasGuid();
        Guid Guid;

        INHERITABLE_PROFILE_SETTING(String, Source);

        Boolean HasConnectionType();
        Guid ConnectionType;

        INHERITABLE_PROFILE_SETTING(Boolean, Hidden);
        INHERITABLE_PROFILE_SETTING(String, Icon);
        INHERITABLE_PROFILE_SETTING(CloseOnExitMode, CloseOnExit);
        INHERITABLE_PROFILE_SETTING(String, TabTitle);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Microsoft.Terminal.Core.Color>, TabColor);
        INHERITABLE_PROFILE_SETTING(Boolean, SuppressApplicationTitle);
        INHERITABLE_PROFILE_SETTING(Boolean, UseAcrylic);
        INHERITABLE_PROFILE_SETTING(Double, AcrylicOpacity);
        INHERITABLE_PROFILE_SETTING(Microsoft.Terminal.Control.ScrollbarState, ScrollState);
        INHERITABLE_PROFILE_SETTING(String, FontFace);
        INHERITABLE_PROFILE_SETTING(Int32, FontSize);
        INHERITABLE_PROFILE_SETTING(Windows.UI.Text.FontWeight, FontWeight);
        INHERITABLE_PROFILE_SETTING(String, Padding);
        INHERITABLE_PROFILE_SETTING(String, Commandline);

        INHERITABLE_PROFILE_SETTING(String, StartingDirectory);
        String EvaluatedStartingDirectory { get; };

        INHERITABLE_PROFILE_SETTING(String, BackgroundImagePath);
        String ExpandedBackgroundImagePath { get; };

        INHERITABLE_PROFILE_SETTING(Double, BackgroundImageOpacity);
        INHERITABLE_PROFILE_SETTING(Windows.UI.Xaml.Media.Stretch, BackgroundImageStretchMode);
        INHERITABLE_PROFILE_SETTING(ConvergedAlignment, BackgroundImageAlignment);
        INHERITABLE_PROFILE_SETTING(Microsoft.Terminal.Control.TextAntialiasingMode, AntialiasingMode);
        INHERITABLE_PROFILE_SETTING(Boolean, RetroTerminalEffect);
        INHERITABLE_PROFILE_SETTING(String, PixelShaderPath);
        INHERITABLE_PROFILE_SETTING(Boolean, ForceFullRepaintRendering);
        INHERITABLE_PROFILE_SETTING(Boolean, SoftwareRendering);
        INHERITABLE_PROFILE_SETTING(String, ColorSchemeName);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Microsoft.Terminal.Core.Color>, Foreground);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Microsoft.Terminal.Core.Color>, Background);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Microsoft.Terminal.Core.Color>, SelectionBackground);
        INHERITABLE_PROFILE_SETTING(Windows.Foundation.IReference<Microsoft.Terminal.Core.Color>, CursorColor);
        INHERITABLE_PROFILE_SETTING(Int32, HistorySize);
        INHERITABLE_PROFILE_SETTING(Boolean, SnapOnInput);
        INHERITABLE_PROFILE_SETTING(Boolean, AltGrAliasing);
        INHERITABLE_PROFILE_SETTING(Microsoft.Terminal.Core.CursorStyle, CursorShape);
        INHERITABLE_PROFILE_SETTING(UInt32, CursorHeight);
        INHERITABLE_PROFILE_SETTING(BellStyle, BellStyle);
    }
}
