// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "IInheritable.idl.h"

namespace Microsoft.Terminal.Settings.Model
{
    // This tag is used to identify the context in which the Profile was created
    enum OriginTag
    {
        Custom = 0,
        InBox,
        Generated
    };

    enum CloseOnExitMode
    {
        Never = 0,
        Graceful,
        Always
    };

    [flags]
    enum BellStyle
    {
        Audible = 0x1,
        Visual = 0x2,
        All = 0xffffffff
    };

    [flags]
    enum ConvergedAlignment {
        // low 4 bits are the horizontal
        Horizontal_Center = 0x00,
        Horizontal_Left = 0x01,
        Horizontal_Right = 0x02,

        // high 4 bits are the vertical
        Vertical_Center = 0x00,
        Vertical_Top = 0x10,
        Vertical_Bottom = 0x20
    };

    [default_interface] runtimeclass Profile {
        Profile();
        Profile(Guid guid);

        OriginTag Origin { get; };

        PROJECTED_SETTING(String, Name);

        Boolean HasGuid();
        Guid Guid;

        PROJECTED_SETTING(String, Source);

        Boolean HasConnectionType();
        Guid ConnectionType;

        PROJECTED_SETTING(Boolean, Hidden);
        PROJECTED_SETTING(String, Icon);
        PROJECTED_SETTING(CloseOnExitMode, CloseOnExit);
        PROJECTED_SETTING(String, TabTitle);
        PROJECTED_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, TabColor);
        PROJECTED_SETTING(Boolean, SuppressApplicationTitle);
        PROJECTED_SETTING(Boolean, UseAcrylic);
        PROJECTED_SETTING(Double, AcrylicOpacity);
        PROJECTED_SETTING(Microsoft.Terminal.TerminalControl.ScrollbarState, ScrollState);
        PROJECTED_SETTING(String, FontFace);
        PROJECTED_SETTING(Int32, FontSize);
        PROJECTED_SETTING(Windows.UI.Text.FontWeight, FontWeight);
        PROJECTED_SETTING(String, Padding);
        PROJECTED_SETTING(String, Commandline);

        PROJECTED_SETTING(String, StartingDirectory);
        String EvaluatedStartingDirectory { get; };

        PROJECTED_SETTING(String, BackgroundImagePath);
        String ExpandedBackgroundImagePath { get; };

        PROJECTED_SETTING(Double, BackgroundImageOpacity);
        PROJECTED_SETTING(Windows.UI.Xaml.Media.Stretch, BackgroundImageStretchMode);
        PROJECTED_SETTING(ConvergedAlignment, BackgroundImageAlignment);
        PROJECTED_SETTING(Microsoft.Terminal.TerminalControl.TextAntialiasingMode, AntialiasingMode);
        PROJECTED_SETTING(Boolean, RetroTerminalEffect);
        PROJECTED_SETTING(String, PixelShaderPath);
        PROJECTED_SETTING(Boolean, ForceFullRepaintRendering);
        PROJECTED_SETTING(Boolean, SoftwareRendering);
        PROJECTED_SETTING(String, ColorSchemeName);
        PROJECTED_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, Foreground);
        PROJECTED_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, Background);
        PROJECTED_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, SelectionBackground);
        PROJECTED_SETTING(Windows.Foundation.IReference<Windows.UI.Color>, CursorColor);
        PROJECTED_SETTING(Int32, HistorySize);
        PROJECTED_SETTING(Boolean, SnapOnInput);
        PROJECTED_SETTING(Boolean, AltGrAliasing);
        PROJECTED_SETTING(Microsoft.Terminal.TerminalControl.CursorStyle, CursorShape);
        PROJECTED_SETTING(UInt32, CursorHeight);
        PROJECTED_SETTING(BellStyle, BellStyle);
    }
}
