// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{

    runtimeclass ThemeColor
    {
        ThemeColor(Microsoft.Terminal.Core.Color color);
        Microsoft.Terminal.Core.Color Color;
    }

    [default_interface] runtimeclass Theme : Windows.Foundation.IStringable {
        Theme();
        Theme(Windows.UI.Xaml.ElementTheme requestedTheme);
        // Theme(String name);

        String Name;

        // window.* Namespace
        Windows.UI.Xaml.ElementTheme RequestedTheme { get; };
        Boolean UseMica { get; };


        // tabRow.* Namespace
        ThemeColor TabRowBackground { get; };

        // Microsoft.Terminal.Core.Color Foreground;
        // Microsoft.Terminal.Core.Color Background;
        // Microsoft.Terminal.Core.Color SelectionBackground;
        // Microsoft.Terminal.Core.Color CursorColor;
    }
}
