// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.UI.Xaml.Markup
{
    interface IXamlMetadataProviderContainer
    {
        Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> Providers { get; };
    };

    [default_interface]
    unsealed runtimeclass XamlApplication : Windows.UI.Xaml.Application, IXamlMetadataProviderContainer, Windows.Foundation.IClosable
    {
        XamlApplication();
        protected XamlApplication(Windows.UI.Xaml.Markup.IXamlMetadataProvider parentProvider);
    }
}
