// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.UI.Xaml.Markup
{
    [default_interface]
    unsealed runtimeclass XamlApplication : Windows.UI.Xaml.Application
    {
        protected XamlApplication(Windows.UI.Xaml.Markup.IXamlMetadataProvider parentProvider);
    }
}
