// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.


namespace SampleApp
{

    [default_interface] runtimeclass SampleAppLogic
    {
        SampleAppLogic();

        void Create(UInt64 hwnd);

        Windows.UI.Xaml.UIElement GetRoot();

        String Title { get; };

    }
}
