// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ActionsViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass NavigateToActionsArgs
    {
        ActionsViewModel ViewModel { get; };
        String ElementToFocus { get; };
    }

    [default_interface] runtimeclass Actions : Windows.UI.Xaml.Controls.Page
    {
        Actions();
        ActionsViewModel ViewModel { get; };
    }
}
