// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass RebindKeysEventArgs
    {
        Microsoft.Terminal.Control.KeyChord OldKeys { get; };
        Microsoft.Terminal.Control.KeyChord NewKeys { get; };
    }

    runtimeclass KeyBindingViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        // Settings Model side
        String Name { get; };
        String KeyChordText { get; };

        // UI side
        Boolean ShowEditButton { get; };
        Boolean IsInEditMode { get; };
        String ProposedKeys;
        Windows.UI.Xaml.Controls.Flyout AcceptChangesFlyout;
        String EditButtonName { get; };
        String CancelButtonName { get; };
        String AcceptButtonName { get; };
        String DeleteButtonName { get; };
        Windows.UI.Xaml.Media.Brush ContainerBackground { get; };

        void EnterHoverMode();
        void ExitHoverMode();
        void FocusContainer();
        void UnfocusContainer();
        void FocusEditButton();
        void UnfocusEditButton();
        void ToggleEditMode();
        void AttemptAcceptChanges();
        void DeleteKeyBinding();

        event Windows.Foundation.TypedEventHandler<KeyBindingViewModel, RebindKeysEventArgs> RebindKeysRequested;
        event Windows.Foundation.TypedEventHandler<KeyBindingViewModel, Microsoft.Terminal.Control.KeyChord> DeleteKeyBindingRequested;
    }

    runtimeclass ActionsPageNavigationState
    {
        Microsoft.Terminal.Settings.Model.CascadiaSettings Settings;
    };

    [default_interface] runtimeclass Actions : Windows.UI.Xaml.Controls.Page
    {
        Actions();
        ActionsPageNavigationState State { get; };

        IObservableVector<KeyBindingViewModel> KeyBindingList { get; };
    }
}
