// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass AddProfilePageNavigationState
    {
        Microsoft.Terminal.Settings.Model.CascadiaSettings Settings;
        void RequestAddNew();
        event Windows.Foundation.TypedEventHandler<Object, Object> AddNew;
    };

    [default_interface] runtimeclass AddProfile : Windows.UI.Xaml.Controls.Page
    {
        AddProfile();
        AddProfilePageNavigationState State { get; };
    }
}
