// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

#include "ViewModelHelpers.idl.h"

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass AISettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AISettingsViewModel(Microsoft.Terminal.Settings.Model.CascadiaSettings settings);

        Boolean AreAzureOpenAIKeyAndEndpointSet { get; };
        String AzureOpenAIEndpoint;
        String AzureOpenAIKey;
        Boolean AzureOpenAIActive;

        Boolean IsOpenAIKeySet { get; };
        String OpenAIKey;
        Boolean OpenAIActive;
    }
}
