// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass ArgsTemplateSelectors : Windows.UI.Xaml.Controls.DataTemplateSelector
    {
        ArgsTemplateSelectors();

        Windows.UI.Xaml.DataTemplate NoArgTemplate;
        Windows.UI.Xaml.DataTemplate GuidTemplate;
        Windows.UI.Xaml.DataTemplate Int32Template;
        Windows.UI.Xaml.DataTemplate Int32OptionalTemplate;
        Windows.UI.Xaml.DataTemplate UInt32Template;
        Windows.UI.Xaml.DataTemplate UInt32OptionalTemplate;
        Windows.UI.Xaml.DataTemplate UInt64Template;
        Windows.UI.Xaml.DataTemplate FloatTemplate;
        Windows.UI.Xaml.DataTemplate StringTemplate;
        Windows.UI.Xaml.DataTemplate BoolOptionalTemplate;
        Windows.UI.Xaml.DataTemplate EnumTemplate;
        Windows.UI.Xaml.DataTemplate FlagTemplate;
        Windows.UI.Xaml.DataTemplate TerminalCoreColorOptionalTemplate;
        Windows.UI.Xaml.DataTemplate WindowsUIColorOptionalTemplate;
    }
}
