// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass BooleanToVisibilityConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        BooleanToVisibilityConverter();
    };
}
