// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ColorSchemeViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{

    runtimeclass ColorSchemesPageNavigationState
    {
        Microsoft.Terminal.Settings.Model.CascadiaSettings Settings;
        String LastSelectedScheme;
        Windows.Foundation.Collections.IObservableVector<ColorSchemeViewModel> AllColorSchemes;
    };

    [default_interface] runtimeclass ColorSchemes : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ColorSchemes();
        ColorSchemesPageNavigationState State { get; };

        Boolean CanDeleteCurrentScheme { get; };
        Boolean IsRenaming { get; };

        ColorSchemeViewModel ColorScheme { get; };

        Windows.Foundation.Collections.IObservableVector<ColorSchemeViewModel> AllColorSchemes { get; };
    }
}
