// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass TerminalColorToBrushConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        TerminalColorToBrushConverter();
    }

    runtimeclass TerminalColorToStringConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        TerminalColorToStringConverter();
    }

    enum ColorType
    {
        RGB,
        Accent,
        TerminalBackground,
        MoreColors
    };

    // TODO CARLOS: add Windows.UI.Xaml.Data.INotifyPropertyChanged
    [default_interface]
    runtimeclass ColorRef : Windows.Foundation.IStringable
    {
        String Name { get; };

        ColorType Type { get; };
        Windows.UI.Color Color { get; };
    }

    [default_interface]
    runtimeclass ColorPickerViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        //ColorPickerViewModel(Microsoft.Terminal.Settings.Model.Profile profile, Microsoft.Terminal.Settings.Model.CascadiaSettings settings);
        ColorRef CurrentColor;

        IObservableVector<ColorRef> ColorList { get; };
    }
}
