// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "ViewModelHelpers.idl.h"

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass CompatibilityViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        CompatibilityViewModel(Microsoft.Terminal.Settings.Model.GlobalAppSettings globalSettings);

        Boolean AllowVtChecksumReportAvailable { get; };
        Boolean AllowKeypadModeAvailable { get; };

        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, ForceVTInput);
        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, AllowVtChecksumReport);
        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, AllowKeypadMode);
        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, AllowHeadless);
        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, IsolatedMode);
    }

    [default_interface] runtimeclass Compatibility : Windows.UI.Xaml.Controls.Page
    {
        Compatibility();
        CompatibilityViewModel ViewModel { get; };
    }
}
