// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "CompatibilityViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass Compatibility : Windows.UI.Xaml.Controls.Page
    {
        Compatibility();
        CompatibilityViewModel ViewModel { get; };
    }
}
