// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{

    runtimeclass ColorLightenConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        ColorLightenConverter();
    };

    runtimeclass FontWeightConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        FontWeightConverter();
    };

    runtimeclass InvertedBooleanConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        InvertedBooleanConverter();
    };

    runtimeclass InvertedBooleanToVisibilityConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        InvertedBooleanToVisibilityConverter();
    };

    runtimeclass ColorToBrushConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        ColorToBrushConverter();
    };

    runtimeclass ColorToHexConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        ColorToHexConverter();
    };

    runtimeclass PercentageConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        PercentageConverter();
    };

    runtimeclass StringIsEmptyConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        StringIsEmptyConverter();
    };

    runtimeclass PaddingConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        PaddingConverter();
    };

    runtimeclass StringIsNotDesktopConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        StringIsNotDesktopConverter();
    };

    runtimeclass DesktopWallpaperToEmptyStringConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        DesktopWallpaperToEmptyStringConverter();
    };
}
