// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass EditAction : Windows.UI.Xaml.Controls.Page
    {
        EditAction();
        String Ayy { get; };
    }
}
