// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ObjectModel/GlobalSettingsModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass GlobalAppearance : Windows.UI.Xaml.Controls.Page
    {
        GlobalAppearance();
        Microsoft.Terminal.Settings.Editor.Model.GlobalSettingsModel GlobalSettingsModel { get; };
    }
}
