// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ObjectModel/GlobalSettingsModel.idl";

namespace SettingsControl
{
    [default_interface] runtimeclass GlobalAppearance : Windows.UI.Xaml.Controls.Page
    {
        GlobalAppearance();
        ObjectModel.GlobalSettingsModel GlobalSettingsModel { get; };
    }
}
