import "SettingsControlViewModel.idl";

namespace SettingsControl
{
    runtimeclass Home : Windows.UI.Xaml.Controls.Page
    {
        Home();
        SettingsControlViewModel HomeViewModel{ get; };
    }
}
