// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "SettingsEditorViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass Home : Windows.UI.Xaml.Controls.Page
    {
        Home();
        SettingsEditorViewModel HomeViewModel{ get; };
    }
}
