// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "GlobalSettingsViewModel.idl";
import "EnumEntry.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass InteractionPageNavigationState
    {
        GlobalSettingsViewModel Globals { get; };
    };

    [default_interface] runtimeclass Interaction : Windows.UI.Xaml.Controls.Page
    {
        Interaction();
        GlobalSettingsViewModel Globals { get; };
    }
}
