// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass InteractionViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        InteractionViewModel(Microsoft.Terminal.Settings.Model.GlobalAppSettings globalSettings);
        Microsoft.Terminal.Settings.Model.GlobalAppSettings GlobalSettings { get; };

        IInspectable CurrentTabSwitcherMode;
        Windows.Foundation.Collections.IObservableVector<Microsoft.Terminal.Settings.Editor.EnumEntry> TabSwitcherModeList { get; };

        IInspectable CurrentCopyFormat;
        Windows.Foundation.Collections.IObservableVector<Microsoft.Terminal.Settings.Editor.EnumEntry> CopyFormatList { get; };
    }
}
