// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface]
    runtimeclass Keybindings : Windows.UI.Xaml.Controls.Page
    {
        Keybindings();
    }
}
