// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass LaunchViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Ayy { get; };
    }
}
