// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass LaunchPageNavigationState
    {
        Microsoft.Terminal.Settings.Model.CascadiaSettings Settings;
    };

    [default_interface] runtimeclass Launch : Windows.UI.Xaml.Controls.Page
    {
        Launch();
        LaunchPageNavigationState State { get; };

        IInspectable CurrentDefaultProfile;

        IInspectable CurrentLaunchMode;
        IObservableVector<Microsoft.Terminal.Settings.Editor.EnumEntry> LaunchModeList { get; };

        IInspectable CurrentWindowingBehavior;
        IObservableVector<Microsoft.Terminal.Settings.Editor.EnumEntry> WindowingBehaviorList { get; };
    }
}
