// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ObjectModel/GlobalSettingsModel.idl";

namespace SettingsControl
{
    [default_interface] runtimeclass Launch : Windows.UI.Xaml.Controls.Page
    {
        Launch();

        ObjectModel.GlobalSettingsModel GlobalSettingsModel { get; };
    }
}
