// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass Launch : Windows.UI.Xaml.Controls.Page
    {
        Launch();

        Microsoft.Terminal.Settings.Model.GlobalAppSettings GlobalSettings { get; };
    }
}
