namespace SettingsControl
{
    [default_interface]
    runtimeclass NewTabOptionPanelControl : Windows.UI.Xaml.Controls.UserControl
    {
        NewTabOptionPanelControl();
        Int32 MyProperty;

        String Argument { get; };
        String InputValue { get; };
    }
}
