// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ProfileViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass Profiles_Base : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Profiles_Base();
        ProfileViewModel Profile { get; };
    }
}
