// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "MainPage.idl";
import "ProfileViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass ProfilePageNavigationState
    {
        ProfileViewModel Profile { get; };
    };

    [default_interface] runtimeclass Profiles : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Profiles();
        ProfileViewModel Profile { get; };

        Windows.UI.Xaml.Controls.Slider OpacitySlider { get; };
    }
}
