// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ObjectModel/GlobalSettingsModel.idl";

namespace SettingsControl
{
    [default_interface] runtimeclass Rendering : Windows.UI.Xaml.Controls.Page
    {
        Rendering();
        ObjectModel.GlobalSettingsModel GlobalSettingsModel { get; };
    }
}
