// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "EnumEntry.idl";

#include "ViewModelHelpers.idl.h"

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass RenderingViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        RenderingViewModel(Microsoft.Terminal.Settings.Model.CascadiaSettings settings);

        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, UseAtlasEngine);
        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, ForceFullRepaintRendering);
        PERMANENT_OBSERVABLE_PROJECTED_SETTING(Boolean, SoftwareRendering);
    }
}
