// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "GlobalSettingsViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass RenderingPageNavigationState
    {
        GlobalSettingsViewModel Globals;
    };

    [default_interface] runtimeclass Rendering : Windows.UI.Xaml.Controls.Page
    {
        Rendering();
        RenderingPageNavigationState State { get; };
    }
}
