// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#pragma once

#include "FilteredSearchResult.g.h"
#include "SearchResultTemplateSelector.g.h"
#include "GeneratedSettingsIndex.g.h"
#include <til/generational.h>
#include "..\TerminalApp\fzf\fzf.h"

class ScopedResourceLoader;

namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
{
    const ScopedResourceLoader& EnglishOnlyResourceLoader() noexcept;

    // Wrapper for IndexEntry objects.
    // Adds neutral locale, if necessary.
    struct LocalizedIndexEntry
    {
        std::optional<winrt::hstring> DisplayTextNeutral = std::nullopt;
        std::optional<winrt::hstring> HelpTextNeutral = std::nullopt;
        const IndexEntry* Entry = nullptr;

        // Retrieves the searchable fields from the LocalizedIndexEntry and their associated weight bonus.
        // This allows us to prioritize certain fields over others when scoring search results.
        std::array<std::pair<std::optional<winrt::hstring>, int>, 4> GetSearchableFields() const
        {
            return { { { std::optional<winrt::hstring>{ Entry->DisplayTextLocalized }, 4 },
                       { Entry->HelpTextLocalized, 3 },
                       { DisplayTextNeutral, 2 },
                       { HelpTextNeutral, 1 } } };
        }
    };

    // WinRT object representing a single filtered search result
    struct FilteredSearchResult : FilteredSearchResultT<FilteredSearchResult>
    {
        FilteredSearchResult(const LocalizedIndexEntry* entry, const Windows::Foundation::IInspectable& navigationArgOverride = nullptr, const std::optional<hstring>& label = std::nullopt, const hstring secondaryLabel = {}) :
            _SearchIndexEntry{ entry },
            _NavigationArgOverride{ navigationArgOverride },
            _overrideLabel{ label },
            _secondaryLabel{ secondaryLabel } {}

        static Editor::FilteredSearchResult CreateNoResultsItem(const winrt::hstring& query);
        static Editor::FilteredSearchResult CreateRuntimeObjectItem(const LocalizedIndexEntry* searchIndexEntry, const Windows::Foundation::IInspectable& runtimeObj);

        hstring ToString() { return Label(); }
        winrt::hstring Label() const;
        winrt::hstring SecondaryLabel() const { return _secondaryLabel; };
        bool IsNoResultsPlaceholder() const;
        const LocalizedIndexEntry& SearchIndexEntry() const noexcept { return *_SearchIndexEntry; }
        Windows::Foundation::IInspectable NavigationArg() const;
        Windows::UI::Xaml::Controls::IconElement Icon() const;

    private:
        const std::optional<winrt::hstring> _overrideLabel{ std::nullopt };
        const winrt::hstring _secondaryLabel{};
        const Windows::Foundation::IInspectable _NavigationArgOverride{ nullptr };
        const LocalizedIndexEntry* _SearchIndexEntry{ nullptr };
    };

    struct SearchResultTemplateSelector : SearchResultTemplateSelectorT<SearchResultTemplateSelector>
    {
        SearchResultTemplateSelector() = default;

        Windows::UI::Xaml::DataTemplate SelectTemplateCore(const Windows::Foundation::IInspectable& item, const Windows::UI::Xaml::DependencyObject& container);
        Windows::UI::Xaml::DataTemplate SelectTemplateCore(const Windows::Foundation::IInspectable& item);

        til::property<winrt::Windows::UI::Xaml::DataTemplate> BasicTemplate;
        til::property<winrt::Windows::UI::Xaml::DataTemplate> ComplexTemplate;
    };

    // The main search index implemented as a singleton.
    // The index loads data generated by tools\GenerateSettingsIndex.ps1 (outputs "Generated Files\GeneratedSettingsIndex.g.h" and cpp).
    // Outputs FilteredSearchResult objects for UI display. UI is determined by SearchResultTemplateSelector.
    class SearchIndex final
    {
    public:
        struct ScoredSearchResult
        {
            const LocalizedIndexEntry* entry;
            int32_t score;
        };

        static SearchIndex& Instance() noexcept
        {
            static SearchIndex instance;
            return instance;
        }

        SearchIndex(const SearchIndex&) = delete;
        SearchIndex& operator=(const SearchIndex&) = delete;
        SearchIndex(SearchIndex&&) = delete;
        SearchIndex& operator=(SearchIndex&&) = delete;

        void Reset();
        Windows::Foundation::IAsyncOperation<Windows::Foundation::Collections::IObservableVector<Windows::Foundation::IInspectable>> SearchAsync(const winrt::hstring& query,
                                                                                                                                                 const Windows::Foundation::Collections::IVectorView<Editor::ProfileViewModel> profileVMs,
                                                                                                                                                 const Windows::Foundation::Collections::IVectorView<Editor::FolderEntryViewModel> ntmFolderVMs,
                                                                                                                                                 const Windows::Foundation::Collections::IVectorView<Editor::ColorSchemeViewModel> colorSchemeVMs,
                                                                                                                                                 const Windows::Foundation::Collections::IVectorView<Editor::ExtensionPackageViewModel> extensionPkgVMs);

    private:
        SearchIndex() = default;
        struct IndexData
        {
            IndexData& operator=(const IndexData& other) = default;

            // Basic index data loaded from GeneratedSettingsIndex.g.h and wrapped as LocalizedIndexEntrys.
            // Non-main indices are duplicated at runtime when searching for runtime objects.
            std::vector<LocalizedIndexEntry> mainIndex;
            std::vector<LocalizedIndexEntry> profileIndex;
            std::vector<LocalizedIndexEntry> ntmFolderIndex;
            std::vector<LocalizedIndexEntry> colorSchemeIndex;

            // Links to main page; used when searching runtime objects
            LocalizedIndexEntry profileIndexEntry;
            LocalizedIndexEntry ntmFolderIndexEntry;
            LocalizedIndexEntry colorSchemeIndexEntry;
            LocalizedIndexEntry extensionIndexEntry;
        } _index;
    };
}

namespace winrt::Microsoft::Terminal::Settings::Editor::factory_implementation
{
    BASIC_FACTORY(SearchResultTemplateSelector);
}
