// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "MainPage.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass FilteredSearchResult : Windows.Foundation.IStringable
    {
        String Label { get; };
        String SecondaryLabel { get; };
        Windows.UI.Xaml.Controls.IconElement Icon { get; };
    }

    runtimeclass SearchResultTemplateSelector : Windows.UI.Xaml.Controls.DataTemplateSelector
    {
        SearchResultTemplateSelector();

        Windows.UI.Xaml.DataTemplate BasicTemplate;
        Windows.UI.Xaml.DataTemplate ComplexTemplate;
    }
}
