// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    enum SettingsCardContentAlignment
    {
        Right,
        Left,
        Vertical
    };

    [default_interface] runtimeclass SettingsCard : Windows.UI.Xaml.Controls.Primitives.ButtonBase
    {
        SettingsCard();

        Object Header;
        static Windows.UI.Xaml.DependencyProperty HeaderProperty { get; };

        Object Description;
        static Windows.UI.Xaml.DependencyProperty DescriptionProperty { get; };

        Windows.UI.Xaml.Controls.IconElement HeaderIcon;
        static Windows.UI.Xaml.DependencyProperty HeaderIconProperty { get; };

        Object ActionIcon;
        static Windows.UI.Xaml.DependencyProperty ActionIconProperty { get; };

        String ActionIconToolTip;
        static Windows.UI.Xaml.DependencyProperty ActionIconToolTipProperty { get; };

        Boolean IsClickEnabled;
        static Windows.UI.Xaml.DependencyProperty IsClickEnabledProperty { get; };

        Boolean IsActionIconVisible;
        static Windows.UI.Xaml.DependencyProperty IsActionIconVisibleProperty { get; };

        SettingsCardContentAlignment ContentAlignment;
        static Windows.UI.Xaml.DependencyProperty ContentAlignmentProperty { get; };
    };

    [default_interface] runtimeclass SettingsCardAutomationPeer : Windows.UI.Xaml.Automation.Peers.ButtonBaseAutomationPeer
    {
        SettingsCardAutomationPeer(SettingsCard owner);
    };
}
