// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace SettingsControl
{
    [default_interface] runtimeclass SplitPaneOptionPanelControl : Windows.UI.Xaml.Controls.UserControl
    {
        SplitPaneOptionPanelControl();

        String Argument();
        String InputValue();
    }
}
