// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass TerminalColorToBrushConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        TerminalColorToBrushConverter();
    }

    runtimeclass TerminalColorToStringConverter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        TerminalColorToStringConverter();
    }
}
