//! One-for-one witness for Microsoft's `KittyKeyboardProtocolTests::KeyPressTests`.
//!
//! Microsoft drives this contract from an exported 132-row data source while
//! forcing the French (Standard, AZERTY) keyboard layout. This Rust witness
//! intentionally keeps the same row granularity instead of sampling semantic
//! families, so every source vector is independently attributable.

use terminal_input::{
    KeyEvent, KeyboardMapper, KittyKeyboardProtocolFlags, KittyKeyboardProtocolMode,
    PortableKeyboardMapper, TerminalInput, control_state, virtual_key,
};

const D: u8 = KittyKeyboardProtocolFlags::DISAMBIGUATE_ESCAPE_CODES;
const E: u8 = KittyKeyboardProtocolFlags::REPORT_EVENT_TYPES;
const A: u8 = KittyKeyboardProtocolFlags::REPORT_ALTERNATE_KEYS;
const K: u8 = KittyKeyboardProtocolFlags::REPORT_ALL_KEYS_AS_ESCAPE_CODES;
const T: u8 = KittyKeyboardProtocolFlags::REPORT_ASSOCIATED_TEXT;

const ALT: u32 = control_state::LEFT_ALT_PRESSED;
const CTRL: u32 = control_state::LEFT_CTRL_PRESSED;
const SHIFT: u32 = control_state::SHIFT_PRESSED;
const CAPS: u32 = control_state::CAPSLOCK_ON;
const NUM: u32 = control_state::NUMLOCK_ON;
const ENH: u32 = control_state::ENHANCED_KEY;
const RALT: u32 = control_state::RIGHT_ALT_PRESSED;

#[derive(Debug, Clone, Copy)]
struct FrenchStandardMapper;

impl KeyboardMapper for FrenchStandardMapper {
    fn unmodified_key(&self, event: &KeyEvent) -> Option<u32> {
        match (event.virtual_key, event.scan_code) {
            (vk, 0x10) if vk == u16::from(b'A') => Some(u32::from(b'a')),
            (vk, 0x02) if vk == u16::from(b'1') => Some(0x00e0),
            _ => PortableKeyboardMapper.unmodified_key(event),
        }
    }

    fn kitty_base_key(&self, event: &KeyEvent, alt_gr: bool) -> Option<u32> {
        match (event.virtual_key, event.scan_code) {
            (vk, 0x10) if vk == u16::from(b'A') => {
                Some(if alt_gr { 0x00e6 } else { u32::from(b'a') })
            }
            (vk, 0x02) if vk == u16::from(b'1') => Some(0x00e0),
            _ => PortableKeyboardMapper.kitty_base_key(event, alt_gr),
        }
    }

    fn kitty_shifted_key(&self, event: &KeyEvent, alt_gr: bool) -> Option<u32> {
        match (event.virtual_key, event.scan_code) {
            (vk, 0x10) if vk == u16::from(b'A') => Some(if alt_gr {
                event.codepoint
            } else {
                u32::from(b'A')
            }),
            (vk, 0x02) if vk == u16::from(b'1') => Some(u32::from(b'1')),
            _ => PortableKeyboardMapper.kitty_shifted_key(event, alt_gr),
        }
    }

    fn kitty_us_base_key(&self, event: &KeyEvent) -> Option<u32> {
        match (event.virtual_key, event.scan_code) {
            (vk, 0x10) if vk == u16::from(b'A') => Some(u32::from(b'q')),
            (vk, 0x02) if vk == u16::from(b'1') => Some(u32::from(b'1')),
            _ => PortableKeyboardMapper.kitty_us_base_key(event),
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct Case {
    name: &'static str,
    expected: &'static str,
    flags: u8,
    key_down: bool,
    virtual_key: u16,
    scan_code: u16,
    codepoint: u32,
    control_key_state: u32,
}

const fn case(
    name: &'static str,
    expected: &'static str,
    flags: u8,
    key_down: bool,
    virtual_key: u16,
    scan_code: u16,
    codepoint: u32,
    control_key_state: u32,
) -> Case {
    Case {
        name,
        expected,
        flags,
        key_down,
        virtual_key,
        scan_code,
        codepoint,
        control_key_state,
    }
}

fn microsoft_cases() -> Vec<Case> {
    vec![
        case("D Esc", "\x1b[27u", D, true, virtual_key::ESCAPE, 1, 0, 0),
        case(
            "D Ctrl+a",
            "\x1b[97;5u",
            D,
            true,
            u16::from(b'A'),
            0x10,
            0,
            CTRL,
        ),
        case(
            "D Ctrl+Alt+a",
            "æ",
            D,
            true,
            u16::from(b'A'),
            0x10,
            0x00e6,
            CTRL | ALT,
        ),
        case(
            "D Shift+Alt+a",
            "\x1b[97;4u",
            D,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT | ALT,
        ),
        case(
            "D Shift+a",
            "A",
            D,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT,
        ),
        case(
            "K a",
            "\x1b[97u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "K Shift+a",
            "\x1b[97;2u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT,
        ),
        case(
            "K Alt+a",
            "\x1b[97;3u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            ALT,
        ),
        case(
            "K Ctrl+a",
            "\x1b[97;5u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            0,
            CTRL,
        ),
        case(
            "K Shift+Alt+a",
            "\x1b[97;4u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT | ALT,
        ),
        case(
            "K Shift+Ctrl+a",
            "\x1b[97;6u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            0,
            SHIFT | CTRL,
        ),
        case(
            "K Ctrl+Alt+a",
            "\x1b[230u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            0x00e6,
            CTRL | ALT,
        ),
        case(
            "K Shift+Ctrl+Alt+a",
            "\x1b[230;2u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            0x00c6,
            SHIFT | CTRL | ALT,
        ),
        case(
            "K CapsLock+a",
            "\x1b[97;65u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            CAPS,
        ),
        case(
            "K NumLock+a",
            "\x1b[97;129u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            NUM,
        ),
        case(
            "K CapsLock+NumLock+a",
            "\x1b[97;193u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            CAPS | NUM,
        ),
        case(
            "K all mods",
            "\x1b[230;194u",
            K,
            true,
            u16::from(b'A'),
            0x10,
            0x00c6,
            SHIFT | CTRL | ALT | CAPS | NUM,
        ),
        case(
            "K Enter",
            "\x1b[13u",
            K,
            true,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            0,
        ),
        case(
            "K Tab",
            "\x1b[9u",
            K,
            true,
            virtual_key::TAB,
            0x0f,
            u32::from(b'\t'),
            0,
        ),
        case(
            "K Backspace",
            "\x1b[127u",
            K,
            true,
            virtual_key::BACK,
            0x0e,
            u32::from(b'\x08'),
            0,
        ),
        case(
            "K Shift+Enter",
            "\x1b[13;2u",
            K,
            true,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            SHIFT,
        ),
        case(
            "K Ctrl+Tab",
            "\x1b[9;5u",
            K,
            true,
            virtual_key::TAB,
            0x0f,
            u32::from(b'\t'),
            CTRL,
        ),
        case(
            "K Alt+Backspace",
            "\x1b[127;3u",
            K,
            true,
            virtual_key::BACK,
            0x0e,
            u32::from(b'\x08'),
            ALT,
        ),
        case(
            "K Shift+Tab",
            "\x1b[9;2u",
            K,
            true,
            virtual_key::TAB,
            0x0f,
            0,
            SHIFT,
        ),
        case(
            "D|E Esc press",
            "\x1b[27u",
            D | E,
            true,
            virtual_key::ESCAPE,
            1,
            0,
            0,
        ),
        case(
            "D|E Esc release",
            "\x1b[27;1:3u",
            D | E,
            false,
            virtual_key::ESCAPE,
            1,
            0,
            0,
        ),
        case(
            "E|K a press",
            "\x1b[97u",
            E | K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "E|K a release",
            "\x1b[97;1:3u",
            E | K,
            false,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "E|K Enter release",
            "\x1b[13;1:3u",
            E | K,
            false,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            0,
        ),
        case(
            "E|K Tab release",
            "\x1b[9;1:3u",
            E | K,
            false,
            virtual_key::TAB,
            0x0f,
            u32::from(b'\t'),
            0,
        ),
        case(
            "E|K Backspace release",
            "\x1b[127;1:3u",
            E | K,
            false,
            virtual_key::BACK,
            0x0e,
            u32::from(b'\x08'),
            0,
        ),
        case(
            "D|E Shift+Esc press",
            "\x1b[27;2u",
            D | E,
            true,
            virtual_key::ESCAPE,
            1,
            0,
            SHIFT,
        ),
        case(
            "D|E Shift+Esc release",
            "\x1b[27;2:3u",
            D | E,
            false,
            virtual_key::ESCAPE,
            1,
            0,
            SHIFT,
        ),
        case(
            "D Numpad0",
            "\x1b[57399u",
            D,
            true,
            virtual_key::NUMPAD0,
            0x52,
            u32::from(b'0'),
            0,
        ),
        case(
            "D Numpad5",
            "\x1b[57404u",
            D,
            true,
            virtual_key::NUMPAD0 + 5,
            0x4c,
            u32::from(b'5'),
            0,
        ),
        case(
            "D Numpad9",
            "\x1b[57408u",
            D,
            true,
            virtual_key::NUMPAD9,
            0x49,
            u32::from(b'9'),
            0,
        ),
        case(
            "D Numpad Decimal",
            "\x1b[57409u",
            D,
            true,
            virtual_key::DECIMAL,
            0x53,
            u32::from(b'.'),
            0,
        ),
        case(
            "D Numpad Divide",
            "\x1b[57410u",
            D,
            true,
            virtual_key::DIVIDE,
            0x35,
            u32::from(b'/'),
            ENH,
        ),
        case(
            "D Numpad Multiply",
            "\x1b[57411u",
            D,
            true,
            virtual_key::MULTIPLY,
            0x37,
            u32::from(b'*'),
            0,
        ),
        case(
            "D Numpad Subtract",
            "\x1b[57412u",
            D,
            true,
            virtual_key::SUBTRACT,
            0x4a,
            u32::from(b'-'),
            0,
        ),
        case(
            "D Numpad Add",
            "\x1b[57413u",
            D,
            true,
            virtual_key::ADD,
            0x4e,
            u32::from(b'+'),
            0,
        ),
        case(
            "D Shift+Numpad5",
            "\x1b[57404;2u",
            D,
            true,
            virtual_key::NUMPAD0 + 5,
            0x4c,
            u32::from(b'5'),
            SHIFT,
        ),
        case(
            "K CapsLock key",
            "\x1b[57358u",
            K,
            true,
            virtual_key::CAPITAL,
            0x3a,
            0,
            0,
        ),
        case(
            "K NumLock key",
            "\x1b[57360u",
            K,
            true,
            virtual_key::NUMLOCK,
            0x45,
            0,
            ENH,
        ),
        case(
            "K ScrollLock key",
            "\x1b[57359u",
            K,
            true,
            virtual_key::SCROLL,
            0x46,
            0,
            0,
        ),
        case(
            "K Left Shift",
            "\x1b[57441;2u",
            K,
            true,
            virtual_key::SHIFT,
            0x2a,
            0,
            SHIFT,
        ),
        case(
            "K Right Shift",
            "\x1b[57447;2u",
            K,
            true,
            virtual_key::SHIFT,
            0x36,
            0,
            SHIFT,
        ),
        case(
            "K Left Ctrl",
            "\x1b[57442;5u",
            K,
            true,
            virtual_key::CONTROL,
            0x1d,
            0,
            CTRL,
        ),
        case(
            "K Right Ctrl",
            "\x1b[57448;5u",
            K,
            true,
            virtual_key::CONTROL,
            0x1d,
            0,
            CTRL | ENH,
        ),
        case(
            "K Left Alt",
            "\x1b[57443;3u",
            K,
            true,
            virtual_key::MENU,
            0x38,
            0,
            ALT,
        ),
        case(
            "K Right Alt",
            "\x1b[57449;3u",
            K,
            true,
            virtual_key::MENU,
            0x38,
            0,
            RALT | ENH,
        ),
        case(
            "K Left Win",
            "\x1b[57444u",
            K,
            true,
            virtual_key::LWIN,
            0x5b,
            0,
            ENH,
        ),
        case(
            "K Right Win",
            "\x1b[57450u",
            K,
            true,
            virtual_key::RWIN,
            0x5c,
            0,
            ENH,
        ),
        case(
            "K Pause",
            "\x1b[57362u",
            K,
            true,
            virtual_key::PAUSE,
            0x45,
            0,
            0,
        ),
        case(
            "K PrintScreen",
            "\x1b[57361u",
            K,
            true,
            virtual_key::SNAPSHOT,
            0x37,
            0,
            ENH,
        ),
        case(
            "K Menu",
            "\x1b[57363u",
            K,
            true,
            virtual_key::APPS,
            0x5d,
            0,
            ENH,
        ),
        case(
            "K Keypad Home",
            "\x1b[57423u",
            K,
            true,
            virtual_key::HOME,
            0x47,
            0,
            0,
        ),
        case(
            "K Keypad End",
            "\x1b[57424u",
            K,
            true,
            virtual_key::END,
            0x4f,
            0,
            0,
        ),
        case(
            "K Keypad Insert",
            "\x1b[57425u",
            K,
            true,
            virtual_key::INSERT,
            0x52,
            0,
            0,
        ),
        case(
            "K Keypad Delete",
            "\x1b[57426u",
            K,
            true,
            virtual_key::DELETE,
            0x53,
            0,
            0,
        ),
        case(
            "K Keypad PageUp",
            "\x1b[57421u",
            K,
            true,
            virtual_key::PRIOR,
            0x49,
            0,
            0,
        ),
        case(
            "K Keypad PageDown",
            "\x1b[57422u",
            K,
            true,
            virtual_key::NEXT,
            0x51,
            0,
            0,
        ),
        case(
            "K Keypad Up",
            "\x1b[57419u",
            K,
            true,
            virtual_key::UP,
            0x48,
            0,
            0,
        ),
        case(
            "K Keypad Down",
            "\x1b[57420u",
            K,
            true,
            virtual_key::DOWN,
            0x50,
            0,
            0,
        ),
        case(
            "K Keypad Left",
            "\x1b[57417u",
            K,
            true,
            virtual_key::LEFT,
            0x4b,
            0,
            0,
        ),
        case(
            "K Keypad Right",
            "\x1b[57418u",
            K,
            true,
            virtual_key::RIGHT,
            0x4d,
            0,
            0,
        ),
        case(
            "K Media Play/Pause",
            "\x1b[57430u",
            K,
            true,
            virtual_key::MEDIA_PLAY_PAUSE,
            0,
            0,
            0,
        ),
        case(
            "K Media Stop",
            "\x1b[57432u",
            K,
            true,
            virtual_key::MEDIA_STOP,
            0,
            0,
            0,
        ),
        case(
            "K Media Next",
            "\x1b[57435u",
            K,
            true,
            virtual_key::MEDIA_NEXT_TRACK,
            0,
            0,
            0,
        ),
        case(
            "K Media Prev",
            "\x1b[57436u",
            K,
            true,
            virtual_key::MEDIA_PREV_TRACK,
            0,
            0,
            0,
        ),
        case(
            "K Volume Down",
            "\x1b[57438u",
            K,
            true,
            virtual_key::VOLUME_DOWN,
            0,
            0,
            0,
        ),
        case(
            "K Volume Up",
            "\x1b[57439u",
            K,
            true,
            virtual_key::VOLUME_UP,
            0,
            0,
            0,
        ),
        case(
            "K Volume Mute",
            "\x1b[57440u",
            K,
            true,
            virtual_key::VOLUME_MUTE,
            0,
            0,
            0,
        ),
        case(
            "K F13",
            "\x1b[57376u",
            K,
            true,
            virtual_key::F13,
            0x64,
            0,
            0,
        ),
        case(
            "K F20",
            "\x1b[57383u",
            K,
            true,
            virtual_key::F20,
            0x6b,
            0,
            0,
        ),
        case(
            "K F24",
            "\x1b[57387u",
            K,
            true,
            virtual_key::F24,
            0x76,
            0,
            0,
        ),
        case(
            "K Shift+F13",
            "\x1b[57376;2u",
            K,
            true,
            virtual_key::F13,
            0x64,
            0,
            SHIFT,
        ),
        case(
            "A|K Shift+a",
            "\x1b[97:65:113;2u",
            A | K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT,
        ),
        case(
            "A|K Shift+1",
            "\x1b[224:49:49;2u",
            A | K,
            true,
            u16::from(b'1'),
            0x02,
            u32::from(b'!'),
            SHIFT,
        ),
        case(
            "A|K a (no shift)",
            "\x1b[97::113u",
            A | K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "K|T Shift+a",
            "\x1b[97;2;65u",
            K | T,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT,
        ),
        case(
            "K|T Shift+1",
            "\x1b[224;2;33u",
            K | T,
            true,
            u16::from(b'1'),
            0x02,
            u32::from(b'!'),
            SHIFT,
        ),
        case(
            "K|T Ctrl+a",
            "\x1b[97;5u",
            K | T,
            true,
            u16::from(b'A'),
            0x10,
            0,
            CTRL,
        ),
        case(
            "K Keypad Enter",
            "\x1b[57414u",
            K,
            true,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            ENH,
        ),
        case(
            "K Regular Enter",
            "\x1b[13u",
            K,
            true,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            0,
        ),
        case(
            "K Shift+Ctrl+Alt+Esc",
            "\x1b[27;8u",
            K,
            true,
            virtual_key::ESCAPE,
            1,
            0,
            SHIFT | CTRL | ALT,
        ),
        case(
            "E|K CapsLock+a",
            "\x1b[97;65u",
            E | K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            CAPS,
        ),
        case(
            "E|K all mods release",
            "\x1b[230;194:3u",
            E | K,
            false,
            u16::from(b'A'),
            0x10,
            0x00c6,
            SHIFT | CTRL | ALT | CAPS | NUM,
        ),
        case("D F1", "\x1b[P", D, true, virtual_key::F1, 0x3b, 0, 0),
        case("D F2", "\x1b[Q", D, true, virtual_key::F1 + 1, 0x3c, 0, 0),
        case("D F3", "\x1b[13~", D, true, virtual_key::F1 + 2, 0x3d, 0, 0),
        case("D F4", "\x1b[S", D, true, virtual_key::F4, 0x3e, 0, 0),
        case(
            "D Shift+F1",
            "\x1b[1;2P",
            D,
            true,
            virtual_key::F1,
            0x3b,
            0,
            SHIFT,
        ),
        case("K F5", "\x1b[15~", K, true, virtual_key::F5, 0x3f, 0, 0),
        case("K F12", "\x1b[24~", K, true, virtual_key::F12, 0x58, 0, 0),
        case(
            "K Shift+F5",
            "\x1b[15;2~",
            K,
            true,
            virtual_key::F5,
            0x3f,
            0,
            SHIFT,
        ),
        case("K Up", "\x1b[A", K, true, virtual_key::UP, 0x48, 0, ENH),
        case("K Down", "\x1b[B", K, true, virtual_key::DOWN, 0x50, 0, ENH),
        case(
            "K Right",
            "\x1b[C",
            K,
            true,
            virtual_key::RIGHT,
            0x4d,
            0,
            ENH,
        ),
        case("K Left", "\x1b[D", K, true, virtual_key::LEFT, 0x4b, 0, ENH),
        case("K Home", "\x1b[H", K, true, virtual_key::HOME, 0x47, 0, ENH),
        case("K End", "\x1b[F", K, true, virtual_key::END, 0x4f, 0, ENH),
        case(
            "K Insert",
            "\x1b[2~",
            K,
            true,
            virtual_key::INSERT,
            0x52,
            0,
            ENH,
        ),
        case(
            "K Delete",
            "\x1b[3~",
            K,
            true,
            virtual_key::DELETE,
            0x53,
            0,
            ENH,
        ),
        case(
            "K PageUp",
            "\x1b[5~",
            K,
            true,
            virtual_key::PRIOR,
            0x49,
            0,
            ENH,
        ),
        case(
            "K PageDown",
            "\x1b[6~",
            K,
            true,
            virtual_key::NEXT,
            0x51,
            0,
            ENH,
        ),
        case(
            "K Shift+Up",
            "\x1b[1;2A",
            K,
            true,
            virtual_key::UP,
            0x48,
            0,
            SHIFT | ENH,
        ),
        case(
            "K Ctrl+Home",
            "\x1b[1;5H",
            K,
            true,
            virtual_key::HOME,
            0x47,
            0,
            CTRL | ENH,
        ),
        case(
            "K Clear",
            "\x1b[E",
            K,
            true,
            virtual_key::CLEAR,
            0x4c,
            0,
            ENH,
        ),
        case(
            "E|K F1 release",
            "\x1b[1;1:3P",
            E | K,
            false,
            virtual_key::F1,
            0x3b,
            0,
            0,
        ),
        case(
            "E|K F5 release",
            "\x1b[15;1:3~",
            E | K,
            false,
            virtual_key::F5,
            0x3f,
            0,
            0,
        ),
        case(
            "E|K Up release",
            "\x1b[1;1:3A",
            E | K,
            false,
            virtual_key::UP,
            0x48,
            0,
            ENH,
        ),
        case(
            "E|K Insert release",
            "\x1b[2;1:3~",
            E | K,
            false,
            virtual_key::INSERT,
            0x52,
            0,
            ENH,
        ),
        case(
            "A|K Shift+Ctrl+a",
            "\x1b[97:65:113;6u",
            A | K,
            true,
            u16::from(b'A'),
            0x10,
            0,
            SHIFT | CTRL,
        ),
        case(
            "K|T a",
            "\x1b[97;;97u",
            K | T,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "E|K|T a release",
            "\x1b[97;1:3u",
            E | K | T,
            false,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "K|T Esc",
            "\x1b[27u",
            K | T,
            true,
            virtual_key::ESCAPE,
            1,
            0,
            0,
        ),
        case(
            "A|K CapsLock+Shift+a",
            "\x1b[97:65:113;66u",
            A | K,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            CAPS | SHIFT,
        ),
        case(
            "A|K|T Shift+a",
            "\x1b[97:65:113;2;65u",
            A | K | T,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT,
        ),
        case(
            "K a release (no EventTypes)",
            "",
            K,
            false,
            u16::from(b'A'),
            0x10,
            u32::from(b'a'),
            0,
        ),
        case(
            "D|E Enter press",
            "\r",
            D | E,
            true,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            0,
        ),
        case(
            "D|E Enter release",
            "",
            D | E,
            false,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            0,
        ),
        case(
            "D|E Keypad Enter release",
            "\x1b[57414;1:3u",
            D | E,
            false,
            virtual_key::RETURN,
            0x1c,
            u32::from(b'\r'),
            ENH,
        ),
        case(
            "D|E Left Shift press",
            "",
            D | E,
            true,
            virtual_key::SHIFT,
            0x2a,
            0,
            SHIFT,
        ),
        case(
            "D|E Left Shift release",
            "",
            D | E,
            false,
            virtual_key::SHIFT,
            0x2a,
            0,
            0,
        ),
        case(
            "E|K Left Shift press",
            "\x1b[57441;2u",
            E | K,
            true,
            virtual_key::SHIFT,
            0x2a,
            0,
            SHIFT,
        ),
        case(
            "E|K Left Shift release",
            "\x1b[57441;1:3u",
            E | K,
            false,
            virtual_key::SHIFT,
            0x2a,
            0,
            0,
        ),
        case(
            "E|K CapsLock press",
            "\x1b[57358u",
            E | K,
            true,
            virtual_key::CAPITAL,
            0x3a,
            0,
            0,
        ),
        case(
            "E|K CapsLock release (now on)",
            "\x1b[57358;65:3u",
            E | K,
            false,
            virtual_key::CAPITAL,
            0x3a,
            0,
            CAPS,
        ),
        case(
            "K|T Shift+a (text)",
            "\x1b[97;2;65u",
            K | T,
            true,
            u16::from(b'A'),
            0x10,
            u32::from(b'A'),
            SHIFT,
        ),
        case(
            "K|T Ctrl+a (control char filtered)",
            "\x1b[97;5u",
            K | T,
            true,
            u16::from(b'A'),
            0x10,
            0,
            CTRL,
        ),
        case(
            "K|T Esc (no text)",
            "\x1b[27u",
            K | T,
            true,
            virtual_key::ESCAPE,
            1,
            0,
            0,
        ),
    ]
}

#[test]
fn microsoft_kitty_keypress_tests_match_every_source_row() {
    let cases = microsoft_cases();
    assert_eq!(cases.len(), 132, "source data row count changed");

    for (index, tc) in cases.into_iter().enumerate() {
        let mut input = TerminalInput::new();
        input.set_kitty_keyboard_protocol(tc.flags, KittyKeyboardProtocolMode::Replace);
        let actual = input.handle_key_with_mapper(
            KeyEvent {
                virtual_key: tc.virtual_key,
                scan_code: tc.scan_code,
                codepoint: tc.codepoint,
                control_key_state: tc.control_key_state,
                key_down: tc.key_down,
                repeat_count: 1,
            },
            &FrenchStandardMapper,
        );

        assert_eq!(
            actual, tc.expected,
            "Microsoft Kitty KeyPressTests row {index}: {}",
            tc.name
        );
    }
}
