// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.UI.Markdown
{
    static runtimeclass Builder
    {
        static Windows.UI.Xaml.Controls.RichTextBlock Convert(String text, String baseUrl);
    };

}
