// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "../ShortcutActionDispatch.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass Action : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Action();

        String Name;
        String IconPath;
        ShortcutAction Command;
    }
}
