// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "../Action.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass ActionList : Windows.UI.Xaml.Controls.Grid
    {
        ActionList();

        Windows.Foundation.Collections.IObservableVector<Action> FilteredActions { get; };
    }
}
