// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include "pch.h"

#include "ActionArgs.h"

#include "CopyTextEventArgs.g.cpp"
#include "PasteTextEventArgs.g.cpp"
#include "NewTabEventArgs.g.cpp"
#include "DuplicateTabEventArgs.g.cpp"
#include "NewTabWithProfileArgs.g.cpp"
#include "NewTabWithProfileEventArgs.g.cpp"
#include "NewWindowEventArgs.g.cpp"
#include "CloseWindowEventArgs.g.cpp"
#include "CloseTabEventArgs.g.cpp"
#include "ClosePaneEventArgs.g.cpp"
#include "NextTabEventArgs.g.cpp"
#include "PrevTabEventArgs.g.cpp"
#include "SplitVerticalEventArgs.g.cpp"
#include "SplitHorizontalEventArgs.g.cpp"
#include "SwitchToTabEventArgs.g.cpp"
#include "IncreaseFontSizeEventArgs.g.cpp"
#include "DecreaseFontSizeEventArgs.g.cpp"
#include "ScrollUpEventArgs.g.cpp"
#include "ScrollDownEventArgs.g.cpp"
#include "ScrollUpPageEventArgs.g.cpp"
#include "ScrollDownPageEventArgs.g.cpp"
#include "OpenSettingsEventArgs.g.cpp"
#include "ResizePaneEventArgs.g.cpp"
#include "MoveFocusEventArgs.g.cpp"
