// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPaneContent.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass AdaptiveCardContent : IPaneContent
    {
        // AdaptiveCardContent();
        // InitFromString(String json);
    }
}

