// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass AppAppearanceConfig : Microsoft.Terminal.TerminalControl.IControlAppearance
    {
        AppAppearanceConfig();
    }
}
