// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass AppCustomConfig : Microsoft.Terminal.TerminalControl.ICustomConfigObj
    {
        AppCustomConfig();
    }
}
