// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
import "ShortcutActionDispatch.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass AppKeyBindings : Microsoft.Terminal.TerminalControl.IKeyBindings
    {
        AppKeyBindings();

        void SetDispatch(ShortcutActionDispatch dispatch);
        void SetKeyMapping(Microsoft.Terminal.Settings.Model.KeyMapping keymap);
    }
}
