// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
import "ShortcutActionDispatch.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass AppKeyBindings : Microsoft.Terminal.Control.IKeyBindings
    {
        AppKeyBindings();

        void SetDispatch(ShortcutActionDispatch dispatch);
        void SetActionMap(Microsoft.Terminal.Settings.Model.IActionMapView actionMap);
    }
}
