// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
import "..\App.idl";

//namespace TerminalApp
//{
//    [default_interface] runtimeclass ColorFlyoutSubItem : Windows.UI.Xaml.Controls.MenuFlyoutSubItem
//    {
//        ColorFlyoutSubItem();
//    }
//}
