import "PaletteItem.idl";
import "TabBase.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass CommandLinePaletteItem : PaletteItem
    {
        CommandLinePaletteItem(String commandLine);

        String CommandLine { get; };
    }
}
