// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ShortcutActionDispatch.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass Command : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Command();

        String Name;
        ActionAndArgs Action;
        String KeyChordText;

        Windows.UI.Xaml.Controls.IconSource IconSource;
        void RefreshIcon();

        Boolean HasNestedCommands { get; };
        Windows.Foundation.Collections.IMapView<String, Command> NestedCommands { get; };
    }
}
