// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPaletteItem.idl";
import "HighlightedTextControl.idl";

namespace TerminalApp
{
    runtimeclass FilteredCommand : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        FilteredCommand();
        FilteredCommand(IPaletteItem item);
        FilteredCommand(IPaletteItem item, Int32 ordinal);

        IPaletteItem Item { get; };
        IVector<HighlightedRun> NameHighlights { get; };
        Int32 Weight;
        Int32 Ordinal { get; };
    }
}
