// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPaletteItem.idl";
import "HighlightedTextControl.idl";

namespace TerminalApp
{
    runtimeclass FilteredCommand : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        FilteredCommand();
        FilteredCommand(IPaletteItem item);

        IPaletteItem Item { get; };
        IVector<HighlightedRun> NameHighlights { get; };
        IVector<HighlightedRun> SubtitleHighlights { get; };
        Boolean HasSubtitle { get; };
        Int32 Weight;
    }
}
