// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "AppLogic.idl";
import "ColorScheme.idl";
import "AppKeybindings.idl";
import "Command.idl";
import "TerminalSettings.idl";

namespace TerminalApp
{
    // MIDL 3 allows for structs to hold nullable types
    // Though IReference is a WinRT object, MIDL 3
    // handles all of the ownership logic for us.
    // Docs: https://docs.microsoft.com/en-us/uwp/midl-3/intro#types
    struct LaunchPosition
    {
        Windows.Foundation.IReference<Int64> X;
        Windows.Foundation.IReference<Int64> Y;
    };

    [default_interface] runtimeclass GlobalAppSettings {
        GlobalAppSettings();

        Guid DefaultProfile;
        String UnparsedDefaultProfile();

        Int32 InitialRows;
        Int32 InitialCols;
        Boolean AlwaysShowTabs;
        Boolean ShowTitleInTitlebar;
        Boolean ConfirmCloseAllTabs;
        Windows.UI.Xaml.ElementTheme Theme;
        Microsoft.UI.Xaml.Controls.TabViewWidthMode TabWidthMode;
        Boolean ShowTabsInTitlebar;
        String WordDelimiters;
        Boolean CopyOnSelect;
        Microsoft.Terminal.TerminalControl.CopyFormat CopyFormatting;
        Boolean WarnAboutLargePaste;
        Boolean WarnAboutMultiLinePaste;
        LaunchPosition InitialPosition;
        LaunchMode LaunchMode;
        Boolean SnapToGridOnResize;
        Boolean ForceFullRepaintRendering;
        Boolean SoftwareRendering;
        Boolean ForceVTInput;
        Boolean DebugFeaturesEnabled;
        Boolean StartOnUserLogin;
        Boolean AlwaysOnTop;
        Boolean UseTabSwitcher;

        Windows.Foundation.Collections.IMapView<String, ColorScheme> GetColorSchemes();
        void AddColorScheme(ColorScheme scheme);

        AppKeyBindings GetKeybindings();

        Windows.Foundation.Collections.IMapView<String, Command> GetCommands();

        void ApplyToSettings(TerminalSettings settings);
    }
}
