// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "HighlightedText.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass HighlightedTextControl : Windows.UI.Xaml.Controls.Control
    {
        HighlightedTextControl();

        HighlightedText Text;
        Windows.UI.Xaml.DependencyProperty TextProperty { get; };

        Windows.UI.Xaml.Style TextBlockStyle;
        Windows.UI.Xaml.DependencyProperty TextBlockStyleProperty { get; };
    }
}
