// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    // C++/winrt makes it difficult to share this idl between two projects,
    // Instead, we just pin the uuid and include it in both TermControl and App
    // If you update this one, please update the one in TerminalControl\TermControl.idl
    // If you change this interface, please update the guid.
    // If you mousewheel and get a runtime error, go make sure both copies are the same.
    [uuid("65b8b8c5-988f-43ff-aba9-e89368da1598")]
    interface IMouseWheelListener
    {
        Boolean OnMouseWheel(Windows.Foundation.Point location, Single delta);
        Boolean OnMouseHWheel(Windows.Foundation.Point location, Single delta);
    }
}
