// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "TerminalTabStatus.idl";

namespace TerminalApp
{
    enum PaletteItemType
    {
        Action,
        CommandLine,
        Tab,
    };

    interface IPaletteItem requires Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PaletteItemType Type { get; };
        String Name { get; };
        String Subtitle { get; };
        String KeyChordText { get; };
        String Icon { get; };
        Windows.UI.Xaml.Controls.IconElement ResolvedIcon { get; };
    }

    runtimeclass TabPaletteItem : [default] IPaletteItem, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        TerminalTabStatus TabStatus{ get; };
    }
}
