// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{

    // Class Description:
    // Encapsulates all tab status indicators
    interface ITabStatus
    {
        Boolean IsPaneZoomed { get; set; };
        Boolean IsProgressRingActive { get; set; };
        Boolean IsProgressRingIndeterminate { get; set; };
        Boolean BellIndicator { get; set; };
        UInt32 ProgressValue { get; set; };
        Boolean IsReadOnlyActive { get; set; };
    }
}
