// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    interface IKeyBindingArgs
    {
        Boolean Handled;
    };

    [default_interface] runtimeclass CopyTextEventArgs : IKeyBindingArgs
    {
        Boolean CopyWhitespace;
    };
    [default_interface] runtimeclass NewTabEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass NewTabWithProfileEventArgs : IKeyBindingArgs
    {
        Int32 ProfileIndex;
    };

    [default_interface] runtimeclass CopyTextEventArgs : IKeyBindingArgs
    {
        Boolean TrimWhitespace;
    };
    [default_interface] runtimeclass PasteTextEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass NewTabEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass DuplicateTabEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass NewTabWithProfileEventArgs : IKeyBindingArgs
    {
        Int32 ProfileIndex;
    };
    [default_interface] runtimeclass NewWindowEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass CloseWindowEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass CloseTabEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass ClosePaneEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass NextTabEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass PrevTabEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass SplitVerticalEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass SplitHorizontalEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass SwitchToTabEventArgs : IKeyBindingArgs
    {
        Int32 ProfileIndex;
    };
    [default_interface] runtimeclass IncreaseFontSizeEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass DecreaseFontSizeEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass ScrollUpEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass ScrollDownEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass ScrollUpPageEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass ScrollDownPageEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass OpenSettingsEventArgs : IKeyBindingArgs{};
    [default_interface] runtimeclass ResizePaneEventArgs : IKeyBindingArgs
    {
        Direction Direction;
    };
    [default_interface] runtimeclass MoveFocusEventArgs : IKeyBindingArgs
    {
        Direction Direction;
    };

}
