// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass LeafPane : Windows.UI.Xaml.Controls.UserControl
    {
        LeafPane();
    }
}
