// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPane.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass LeafPane : Windows.UI.Xaml.Controls.UserControl, IPane
    {
        LeafPane();
    }
}
