// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPane.idl";

namespace TerminalApp
{
    enum BordersEnum
    {
        None = 0,
        Top = 1,
        Bottom = 2,
        Left = 4,
        Right = 8
    };

    [default_interface] runtimeclass LeafPane : Windows.UI.Xaml.Controls.UserControl, IPane
    {
        LeafPane(Guid profile, Microsoft.Terminal.Control.TermControl con, Boolean active);

        UInt32 Id;
        BordersEnum Borders;
        Microsoft.Terminal.Control.TermControl TerminalControl { get; };
        Guid Profile { get; };

        Boolean WasLastFocused();
        void SetActive();
        void Close();
        void UpdateBorders();
        void UpdateBorderWithClosedNeighbor(LeafPane closedNeighbor, Microsoft.Terminal.Settings.Model.ResizeDirection neighborDirection);
        LeafPane Split(Microsoft.Terminal.Settings.Model.SplitState splitType, Single splitSize, Guid profile, Microsoft.Terminal.Control.TermControl con);
    }
}
