namespace TerminalApp
{
    [default_interface] runtimeclass MinMaxCloseControl : Windows.UI.Xaml.Controls.StackPanel
    {
        MinMaxCloseControl();

        void Maximize();
        void RestoreDown();

        // Windows.UI.Xaml.Controls.Button MinimizeButton { get; };
        Windows.UI.Xaml.Controls.Button MaximizeButton { get; };
        Windows.UI.Xaml.Controls.Button CloseButton { get; };

        event Windows.Foundation.TypedEventHandler<MinMaxCloseControl, Windows.UI.Xaml.RoutedEventArgs> MinimizeClick;
    }
}
