// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "..\TitlebarControl.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass MinMaxCloseControl : Windows.UI.Xaml.Controls.StackPanel
    {
        MinMaxCloseControl();

        void SetWindowVisualState(WindowVisualState visualState);

        event Windows.Foundation.TypedEventHandler<MinMaxCloseControl, Windows.UI.Xaml.RoutedEventArgs> MinimizeClick;
        event Windows.Foundation.TypedEventHandler<MinMaxCloseControl, Windows.UI.Xaml.RoutedEventArgs> MaximizeClick;
        event Windows.Foundation.TypedEventHandler<MinMaxCloseControl, Windows.UI.Xaml.RoutedEventArgs> CloseClick;
    }
}
