// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPane.idl";
import "LeafPane.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass ParentPane : Windows.UI.Xaml.Controls.UserControl, IPane
    {
        ParentPane(LeafPane firstChild, LeafPane secondChild, Microsoft.Terminal.Settings.Model.SplitState splitState, Single splitPosition, Windows.Foundation.Size currentSize);
        void InitializeChildren();
    }
}
