// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPane.idl";
import "LeafPane.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass ParentPane : Windows.UI.Xaml.Controls.UserControl, IPane
    {
        ParentPane(LeafPane firstChild, LeafPane secondChild, Microsoft.Terminal.Settings.Model.SplitState splitState, Single splitPosition);
        void InitializeChildren();
        Boolean ResizePane(Microsoft.Terminal.Settings.Model.ResizeDirection direction);
        Boolean NavigateFocus(Microsoft.Terminal.Settings.Model.FocusDirection direction);
        void Relayout();
    }
}
