// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass ParentPane : Windows.UI.Xaml.Controls.UserControl
    {
        ParentPane();
    }
}
