// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "TabBase.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass SettingsTab : TabBase
    {
    }
}
