// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
import "ShortcutActionDispatch.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass Tab : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Title { get; };
        Windows.UI.Xaml.Controls.IconSource IconSource { get; };
        Microsoft.Terminal.Settings.Model.Command SwitchToTabCommand { get; };
        UInt32 TabViewIndex { get; };

        Windows.UI.Xaml.UIElement Content { get; };

        void SetDispatch(ShortcutActionDispatch dispatch);
    }
}
