// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    delegate void HeaderTitleChangedArgs();

    [default_interface] runtimeclass TabHeaderControl : Windows.UI.Xaml.Controls.UserControl
    {
        TabHeaderControl();
        String CurrentHeaderText();
        void UpdateHeaderText(String title);
        void SetZoomIcon(Windows.UI.Xaml.Visibility state);
        void ConstructTabRenameBox();

        event HeaderTitleChangedArgs HeaderTitleChanged;
    }
}
