// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass TaskbarState
    {
        TaskbarState();
        TaskbarState(Microsoft.Terminal.Control.TaskbarState state, UInt64 progress);

        Microsoft.Terminal.Control.TaskbarState State{ get; };
        UInt64 Progress{ get; };
        UInt64 Priority { get; };
    }
}
