// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IPaneContent.idl";
import "TerminalSettingsCache.idl";
import "FilteredCommand.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass TerminalPaneContent : IPaneContent, ISnappable
    {
        Microsoft.Terminal.Control.TermControl GetTermControl();

        void UpdateTerminalSettings(TerminalSettingsCache cache);

        void MarkAsDefterm();

        Microsoft.Terminal.Settings.Model.Profile GetProfile();

        event Windows.Foundation.TypedEventHandler<TerminalPaneContent, Object> RestartTerminalRequested;
    }


    [default_interface] runtimeclass ScratchpadContent : IPaneContent
    {
    }
    [default_interface] runtimeclass SettingsPaneContent : IPaneContent
    {
        SettingsPaneContent(Microsoft.Terminal.Settings.Model.CascadiaSettings settings);
    }

    [default_interface] runtimeclass FilteredTask : TerminalApp.FilteredCommand
    {
        String Input{ get; };
        Windows.Foundation.Collections.IObservableVector<FilteredTask> Children { get; };
        Windows.UI.Xaml.Visibility Visibility { get; };
    }

    [default_interface] runtimeclass TasksPaneContent : Windows.UI.Xaml.Controls.UserControl, IPaneContent
    {
        TasksPaneContent();
        void SetLastActiveControl(Microsoft.Terminal.Control.TermControl control);

        event Windows.Foundation.TypedEventHandler<Object, Microsoft.Terminal.Settings.Model.Command> DispatchCommandRequested;

    }

}
