// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "TabBase.idl";
import "TerminalTabStatus.idl";

namespace Microsoft.Terminal.App
{
    [default_interface] runtimeclass TerminalTab : TabBase
    {
        TerminalTabStatus TabStatus { get; };
    }
}
