// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{    
    [default_interface] runtimeclass TerminalBackground : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        TerminalBackground();
        Windows.UI.Xaml.Media.SolidColorBrush Brush;
    }
}
