// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass TitlebarControl : Windows.UI.Xaml.Controls.Grid
    {
        TitlebarControl(UInt64 parentWindowHandle);

        IInspectable Content;
        Windows.UI.Xaml.Controls.Border DragBar { get; };
    }
}
