// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass Toaster
    {
        Toaster(Windows.UI.Xaml.Controls.Panel root);
        void MakeToast(String title, String subtitle, Windows.UI.Xaml.FrameworkElement target);
    }
}
