// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ControlInteractivity.idl";

namespace Microsoft.Terminal.Control
{
    runtimeclass ContentProcess {

        ContentProcess(Guid g);

        Boolean Initialize(IControlSettings settings,
                           IControlAppearance unfocusedAppearance,
                           Microsoft.Terminal.TerminalConnection.ConnectionInformation connectionInfo);

        ControlInteractivity GetInteractivity();

        UInt64 GetPID();

        UInt64 RequestSwapChainHandle(UInt64 pid);

        Guid Guid { get; };

        void Attach();
        event Windows.Foundation.TypedEventHandler<Object, Object> Attached;

    };
}
