// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ICoreState.idl";
import "IControlSettings.idl";
import "ControlCore.idl";
import "EventArgs.idl";
import "InteractivityAutomationPeer.idl";


namespace Microsoft.Terminal.Control
{

    [default_interface] runtimeclass ControlInteractivity
    {
        ControlInteractivity(IControlSettings settings,
                             Microsoft.Terminal.TerminalConnection.ITerminalConnection connection);

        ControlCore GetCore();
        void UpdateSettings(Microsoft.Terminal.Core.Padding padding);
        void Initialize();
        void GainFocus();
        void LostFocus();

        InteractivityAutomationPeer OnCreateAutomationPeer();

        Boolean CopySelectionToClipboard(Boolean singleLine, Windows.Foundation.IReference<CopyFormat> formats);
        void RequestPasteTextFromClipboard();
        void SetEndSelectionPoint(Microsoft.Terminal.Core.Point point);

        void PointerPressed(Microsoft.Terminal.Core.MouseButtonState buttonState,
                            UInt32 pointerUpdateKind,
                            UInt64 timestamp,
                            Microsoft.Terminal.Core.ControlKeyStates modifiers,
                            Microsoft.Terminal.Core.Point pixelPosition);
        void TouchPressed(Microsoft.Terminal.Core.Point contactPoint);

        void PointerMoved(Microsoft.Terminal.Core.MouseButtonState buttonState,
                          UInt32 pointerUpdateKind,
                          Microsoft.Terminal.Core.ControlKeyStates modifiers,
                          Boolean focused,
                          Microsoft.Terminal.Core.Point pixelPosition);
        void TouchMoved(Microsoft.Terminal.Core.Point newTouchPoint,
                        Boolean focused);

        void PointerReleased(Microsoft.Terminal.Core.MouseButtonState buttonState,
                             UInt32 pointerUpdateKind,
                             Microsoft.Terminal.Core.ControlKeyStates modifiers,
                             Microsoft.Terminal.Core.Point pixelPosition);
        void TouchReleased();

        Boolean MouseWheel(Microsoft.Terminal.Core.ControlKeyStates modifiers,
                           Int32 delta,
                           Microsoft.Terminal.Core.Point pixelPosition,
                           Microsoft.Terminal.Core.MouseButtonState state);

        void UpdateScrollbar(Double newValue);

        event Windows.Foundation.TypedEventHandler<Object, OpenHyperlinkEventArgs> OpenHyperlink;
        event Windows.Foundation.TypedEventHandler<Object, ScrollPositionChangedArgs> ScrollPositionChanged;
        event Windows.Foundation.TypedEventHandler<Object, PasteFromClipboardEventArgs> PasteFromClipboard;


    };
}
