// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ControlInteractivity.idl";

namespace Microsoft.Terminal.Control
{
    runtimeclass ContentProcess {

        ContentProcess();

        Boolean Initialize(IControlSettings settings,
                           Microsoft.Terminal.TerminalConnection.ConnectionInformation connectionInfo);

        ControlInteractivity GetInteractivity();

        UInt64 RequestSwapChainHandle(UInt64 pid);
    };
}
