// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "IKeyBindings.idl";

namespace Microsoft.Terminal.TerminalControl
{
    enum ScrollbarState
    {
        Visible = 0,
        Hidden
    };

    enum TextAntialiasingMode
    {
        Grayscale = 0,
        Cleartype,
        Aliased
    };

    // Class Description:
    // TerminalSettings encapsulates all settings that control the
    //      TermControl's behavior. In these settings there is both the entirety
    //      of the Core ITerminalSettings interface, and any additional settings
    //      for specifically the control.
    interface IControlSettings requires ICoreSettings
    {
        String ProfileName { get; };

        Boolean UseAcrylic { get; };
        Double TintOpacity { get; };
        ScrollbarState ScrollState { get; };

        String FontFace { get; };
        Int32 FontSize { get; };
        Windows.UI.Text.FontWeight FontWeight { get; };
        String Padding { get; };

        Microsoft.Terminal.TerminalControl.IKeyBindings KeyBindings { get; };

        Boolean CopyOnSelect { get; };

        String Commandline { get; };
        String StartingDirectory { get; };
        String EnvironmentVariables { get; };

        String BackgroundImage { get; };
        Double BackgroundImageOpacity { get; };
        Windows.UI.Xaml.Media.Stretch BackgroundImageStretchMode { get; };
        Windows.UI.Xaml.HorizontalAlignment BackgroundImageHorizontalAlignment { get; };
        Windows.UI.Xaml.VerticalAlignment BackgroundImageVerticalAlignment { get; };

        UInt32 SelectionBackground { get; };

        TextAntialiasingMode AntialiasingMode { get; };

        Boolean RetroTerminalEffect { get; };
        Boolean ForceFullRepaintRendering { get; };
        Boolean SoftwareRendering { get; };
    };
}
