// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "KeyChord.idl";

namespace Microsoft.Terminal.Control
{
    // [default_interface]
    interface IKeyBindings
    {
        Boolean TryKeyChord(KeyChord kc);
        Boolean IsKeyChordExplicitlyUnbound(KeyChord kc);
    }
}
