// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Control
{
    [default_interface]
    runtimeclass KeyChord
    {
        KeyChord();
        KeyChord(Windows.System.VirtualKeyModifiers modifiers, Int32 vkey, Int32 scanCode);
        KeyChord(Boolean ctrl, Boolean alt, Boolean shift, Boolean win, Int32 vkey, Int32 scanCode);

        UInt64 Hash();
        Boolean Equals(KeyChord other);

        Windows.System.VirtualKeyModifiers Modifiers;
        Int32 Vkey;
        Int32 ScanCode;
    }
}
