// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalControl
{
    delegate void CompositionCompletedEventArgs(String text);

    runtimeclass CursorPositionEventArgs
    {
        Windows.Foundation.Point CurrentPosition { get; set; };
    }

    runtimeclass FontInfoEventArgs
    {
        String FontFace { get; set; };
        Windows.Foundation.Point FontSize { get; set; };
    }

    [default_interface]
    runtimeclass TSFInputControl : Windows.UI.Xaml.Controls.UserControl
    {
        TSFInputControl();

        static Windows.UI.Xaml.DependencyProperty FontHeightProperty{ get; };
        Double FontHeight;

        static Windows.UI.Xaml.DependencyProperty FontWidthProperty{ get; };
        Double FontWidth;

        event CompositionCompletedEventArgs CompositionCompleted;
        event Windows.Foundation.TypedEventHandler<TSFInputControl, CursorPositionEventArgs> CurrentCursorPosition;
        event Windows.Foundation.TypedEventHandler<TSFInputControl, FontInfoEventArgs> CurrentFontInfo;

        void NotifyFocusEnter();
        void NotifyFocusLeave();
    }
}
