// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Control
{
    [default_interface] runtimeclass XamlUiaTextRange :
        Windows.UI.Xaml.Automation.Provider.ITextRangeProvider
    {
    }
}
