//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WindowsTerminal.rc
//
#define IDI_APPICON 101
#define IDI_APPICON_HC_B 102
#define IDI_APPICON_HC_W 103

#define IDI_APPICON_DEV 104
#define IDI_APPICON_DEV_HC_B 105
#define IDI_APPICON_DEV_HC_W 106

#define IDI_APPICON_PRE 107
#define IDI_APPICON_PRE_HC_B 108
#define IDI_APPICON_PRE_HC_W 109

#define IDS_ERROR_DIALOG_TITLE 110
#define IDS_HELP_DIALOG_TITLE 111
#define IDS_ERROR_ARCHITECTURE_FORMAT 112
#define IDS_X86_ARCHITECTURE 113
#define IDS_AMD64_ARCHITECTURE 114
#define IDS_ARM64_ARCHITECTURE 115
#define IDS_ARM_ARCHITECTURE 116
#define IDS_UNKNOWN_ARCHITECTURE 117

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 118
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
