// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ILLMProvider.idl";

namespace Microsoft.Terminal.Query.Extension
{
    [default_interface] runtimeclass AzureLLMProvider : ILLMProvider
    {
        AzureLLMProvider(String endpt, String key);

        String Thing();
    }
}
