// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Query.Extension
{
    interface ILMProvider
    {
        // chat related functions
        void ClearMessageHistory();
        void SetSystemPrompt(String systemPrompt);
        void SetContext(IContext context);

        Windows.Foundation.IAsyncOperation<IResponse> GetResponseAsync(String userPrompt);

        // auth related functions
        void CompleteAuthWithUrl(String url);
        event Windows.Foundation.TypedEventHandler<ILMProvider, String> AuthChanged;
    }

    interface IResponse
    {
        String Message { get; };
        Boolean IsError { get; };
    };

    interface IContext
    {
        String ActiveCommandline { get; };
    };
}
