// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Query.Extension
{
    interface IBrandingData
    {
        String Name { get; };
        String HeaderIconPath { get; };
        String HeaderText { get; };
        String SubheaderText { get; };
        String BadgeIconPath { get; };
        String ResponseMetaData { get; };
        String QueryMetaData { get; };
    };

    interface IAuthenticationResult
    {
        String ErrorMessage { get; };
        Windows.Foundation.Collections.ValueSet AuthValues { get; };
    };

    interface ILMProvider
    {
        // chat related functions
        void ClearMessageHistory();
        void SetSystemPrompt(String systemPrompt);
        void SetContext(IContext context);

        Windows.Foundation.IAsyncOperation<IResponse> GetResponseAsync(String userPrompt);

        // auth related functions
        void SetAuthentication(Windows.Foundation.Collections.ValueSet authValues);
        event Windows.Foundation.TypedEventHandler<ILMProvider, IAuthenticationResult> AuthChanged;

        // UI related settings
        IBrandingData BrandingData { get; };
    }

    enum ErrorTypes
    {
        None = 0,
        InvalidAuth,
        InvalidModel,
        FromProvider,
        Unknown
    };

    interface IResponse
    {
        String Message { get; };
        ErrorTypes ErrorType { get; };
    };

    interface IContext
    {
        String ActiveCommandline { get; };
    };
}
