// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Query.Extension
{
    interface ILMProvider
    {
        void ClearMessageHistory();
        void SetSystemPrompt(String systemPrompt);
        void SetContext(IContext context);

        Windows.Foundation.IAsyncOperation<IResponse> GetResponseAsync(String userPrompt);
    }

    interface IResponse
    {
        String Message { get; };
        Boolean IsError { get; };
    };

    interface IContext
    {
        String ActiveCommandline { get; };
    };
}
