@echo off

rem openbash - launch bash running in the generated OpenConsole binary
rem Runs the OpenConsole.exe binary generated by the build in the debug directory.
rem    Defaults to your `~` directory.

call opencon bash ~