@echo off

rem openps - launch Powershell running in the generated OpenConsole binary
rem Runs the OpenConsole.exe binary generated by the build in the debug directory.

call opencon powershell.exe