@echo off

rem opencon - launch the openconsole binary.
rem Runs the WindowsTerminal.exe binary generated by the build in the debug directory.
rem    Passes any args along.

set TARGET=WindowsTerminal.exe

if not exist %OPENCON%\%PLATFORM%\%_LAST_BUILD_CONF%\%TARGET% (
    echo Could not locate the %TARGET% in %OPENCON%\bin\%PLATFORM%\%_LAST_BUILD_CONF%. Double check that it has been built and try again.
    goto :eof
)

setlocal
rem Generate a unique name, so that we can debug multiple revisions of the binary at the same time if needed.
set rand_val=%random%
set _r=%random%
set _last_build=%OPENCON%\bin\%PLATFORM%\%_LAST_BUILD_CONF%
set _last_cascadia_build=%OPENCON%\%PLATFORM%\%_LAST_BUILD_CONF%
set copy_dir=OpenConsole\%_r%
set cascadia_copy_dir=OpenConsole\%_r%\Cascadia

(xcopy /Y %_last_build%\OpenConsole.exe %TEMP%\%copy_dir%\OpenConsole.exe*) > nul
(xcopy /Y %_last_build%\OpenConsole.exe %TEMP%\%cascadia_copy_dir%\conhost.exe*) > nul
(xcopy /Y %_last_build%\VtPipeTerm.exe %TEMP%\%copy_dir%\VtPipeTerm.exe*) > nul
(xcopy /Y %_last_build%\Nihilist.exe %TEMP%\%copy_dir%\Nihilist.exe*) > nul
(xcopy /Y %_last_build%\console.dll %TEMP%\%copy_dir%\console.dll*) > nul
(xcopy /Y %_last_cascadia_build%\%TARGET% %TEMP%\%cascadia_copy_dir%\%TARGET%*) > nul
(xcopy /Y %_last_cascadia_build%\TerminalConnection.dll %TEMP%\%cascadia_copy_dir%\TerminalConnection.dll*) > nul
(xcopy /Y %_last_cascadia_build%\TerminalControl.dll %TEMP%\%cascadia_copy_dir%\TerminalControl.dll*) > nul
(xcopy /Y %_last_cascadia_build%\TerminalSettings.dll %TEMP%\%cascadia_copy_dir%\TerminalSettings.dll*) > nul
(xcopy /Y %_last_cascadia_build%\TerminalApp.dll %TEMP%\%cascadia_copy_dir%\TerminalApp.dll*) > nul

echo Launching %TEMP%\%cascadia_copy_dir%\%TARGET%...
start %TEMP%\%cascadia_copy_dir%\%TARGET% %*
