//Autogenerated file name + version resource file for Device Guard whitelisting effort

#include <windows.h>
#include <ntverp.h>

#define VER_FILETYPE    VFT_UNKNOWN
#define VER_FILESUBTYPE VFT2_UNKNOWN
#define VER_FILEDESCRIPTION_STR     ___TARGETNAME
#define VER_INTERNALNAME_STR        ___TARGETNAME
#define VER_ORIGINALFILENAME_STR    ___TARGETNAME

#include "common.ver"
