<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildThisFileDirectory)..\Microsoft.Windows.Terminal.Control.targets" />
  <ItemGroup>
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-$(TerminalNativePlatform)\native\*.dll" />
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-$(TerminalNativePlatform)\native\*.pri" />
  </ItemGroup>
</Project>
