// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalControl
{
    enum CursorStyle
    {
        Vintage,
        Bar,
        Underscore,
        FilledBox,
        EmptyBox
    };

    // [default_interface]
    interface IAppearance
    {
        UInt32 GetColorTableEntry(Int32 index);
        UInt32 DefaultForeground { get; set; };
        UInt32 DefaultBackground { get; set; };
        UInt32 CursorColor { get; set; };
        UInt32 SelectionBackground { get; set; };
        CursorStyle CursorShape;
        String BackgroundImage { get; set; };
    };
}
