// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalControl
{
    // [default_interface]
    interface IAppearance
    {
        UInt32 DefaultForeground { get; set; };
        UInt32 DefaultBackground { get; set; };
        UInt32 CursorColor { get; set; };
        UInt32 SelectionBackground { get; set; };
        //CursorStyle CursorShape;
        String BackgroundImage { get; set; };
    };
}
