// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "..\ICoreAppearance.idl";

namespace Microsoft.Terminal.Core
{
    interface ICoreSettings requires ICoreAppearance
    {
        // TODO:MSFT:20642297 - define a sentinel for Infinite Scrollback
        Int32 HistorySize { get; };
        Int32 InitialRows { get; };
        Int32 InitialCols { get; };

        Boolean SnapOnInput { get; };
        Boolean AltGrAliasing { get; };
        String AnswerbackMessage { get; };

        String StartingTitle { get; };
        Boolean SuppressApplicationTitle { get; };
        String WordDelimiters { get; };

        Boolean ForceVTInput { get; };
        Boolean AllowVtChecksumReport { get; };
        Boolean AllowVtClipboardWrite { get; };
        Boolean TrimBlockSelection { get; };
        Boolean DetectURLs { get; };

        Windows.Foundation.IReference<Microsoft.Terminal.Core.Color> TabColor { get; };
        Windows.Foundation.IReference<Microsoft.Terminal.Core.Color> StartingTabColor { get; };

        Boolean AutoMarkPrompts { get; };
        Boolean RainbowSuggestions { get; };

        // NOTE! When adding something here, make sure to update ControlProperties.h too!
    };

}
