// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalControl
{
    enum CursorStyle
    {
        Vintage,
        Bar,
        Underscore,
        FilledBox,
        EmptyBox
    };

    interface ICoreSettings
    {
        UInt32 DefaultForeground { get; };
        UInt32 DefaultBackground { get; };
        UInt32 GetColorTableEntry(Int32 index);
        void SetColorTableEntry(Int32 index, UInt32 value);
        // TODO:MSFT:20642297 - define a sentinel for Infinite Scrollback
        Int32 HistorySize { get; };
        Int32 InitialRows { get; };
        Int32 InitialCols { get; };

        Boolean SnapOnInput { get; };
        Boolean AltGrAliasing { get; };

        UInt32 CursorColor { get; };
        CursorStyle CursorShape { get; };
        UInt32 CursorHeight { get; };
        String StartingTitle { get; };
        Boolean SuppressApplicationTitle { get; };
        String WordDelimiters { get; };

        Boolean ForceVTInput { get; };
    };

}
