// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.ShellExtension
{
    [default_interface] runtimeclass PlaceholderType {
        PlaceholderType();
        Int32 Placeholder
        {
            get;
            set;
        };
    };

}
