name: Add triaged bugs & tasks to project board
# https://github.com/actions/add-to-project

on:
  issues:
    types:
      - labeled
      - unlabeled

permissions: {}
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/microsoft/projects/159
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Issue-Feature, Needs-Triage, Needs-Author-Feedback, Issue-Scenario
          label-operator: NOT
