name: Build Terminal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up NuGet (for Windows implementation library & Taef)
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      # Step 3: Restore NuGet packages
      - name: NuGet Restore
        run: nuget restore "D:/a/terminal/terminal/OpenConsole.slnx"

      # Step 4: Download and bootstrap vcpkg
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg-tool.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      # Step 5: Install all vcpkg packages from manifest
      - name: Install vcpkg dependencies
        run: .\vcpkg\vcpkg install

      # Step 6: Build solution using MSBuild
      - name: Build Solution
        run: |
          msbuild "D:/a/terminal/terminal/OpenConsole.slnx" /p:Configuration=Release /p:Platform=x64

      # Optional: Cache vcpkg to speed up subsequent runs
      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg/installed
          key: vcpkg-cache-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-cache-${{ runner.os }}-
