name: Build Terminal

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup NuGet (so missing packages can restore)
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: 6.6.1  # match your project version

      # 3️⃣ Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore D:\a\terminal\terminal\OpenConsole.slnx

      # 4️⃣ Download vcpkg
      - name: Download vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg-tool.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      # 5️⃣ Install vcpkg dependencies from manifest
      - name: Install vcpkg dependencies
        run: .\vcpkg\vcpkg install

      # 6️⃣ Build solution
      - name: Build solution
        run: |
          msbuild D:\a\terminal\terminal\OpenConsole.slnx /p:Configuration=Release /p:Platform=x64 /m

      # 7️⃣ Optional: run tests
      - name: Run tests
        run: |
          msbuild D:\a\terminal\terminal\OpenConsole.slnx /t:Test /p:Configuration=Release /p:Platform=x64

