name=.github/workflows/msbuild.yml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages for Scratch.sln
      working-directory: ${{github.workspace}}
      run: nuget restore Scratch.sln

    - name: Build Scratch.sln
      working-directory: ${{github.workspace}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} Scratch.sln

    - name: Restore NuGet packages for OpenConsole.slnx
      working-directory: ${{github.workspace}}
      run: nuget restore OpenConsole.slnx

    - name: Build OpenConsole.slnx
      working-directory: ${{github.workspace}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} OpenConsole.slnx
